Table profiles as P {
    id serial [pk]
    account_id integer [not null]
    display_name varchar(200) [not null]
    summary text [not null]
    city varchar(200) [not null]
    state varchar(200)
    country varchar(2) [not null]
    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (account_id) [unique, name: 'profiles_account_id_uidx']
    }
}

Table profile_pictures as PP {
    id uuid [pk]
    ext varchar(10) [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [unique, name: 'profile_picture_profile_id_uidx']
        (account_id) [unique, name: 'profile_picture_account_id_uidx']
    }
}
Ref: PP.profile_id > P.id [delete: cascade]

Table social_links as SL {
    id serial [pk]

    name varchar(50) [not null]
    url text [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'social_links_profile_id_idx']
        (account_id) [name: 'social_links_account_id_idx']
        (profile_id, name) [unique, name: 'social_links_profile_id_name_uidx']
    }
}
Ref: SL.profile_id > P.id [delete: cascade]
Ref: SL.account_id > A.id [delete: cascade]

// Table custom_domain as CD {
//     id serial [pk]

//     domain varchar(200) [not null]

//     profile_id integer [not null]
//     account_id integer [not null]

//     created_at timestamp [not null, default: `now()`]
//     updated_at timestamp [not null, default: `now()`]

//     Indexes {
//         (domain) [unique, name: 'custom_domain_domain_uidx']
//         (profile_id) [unique, name: 'custom_domain_profile_id_uidx']
//         (account_id) [unique, name: 'custom_domain_account_id_uidx']
//     }
// }
// Ref: CD.profile_id > P.id [delete: cascade]

// TODO: add theme when I decided the design

Table experiences as E {
    id serial [pk]

    title varchar(200) [not null]
    company varchar(200) [not null]
    city varchar(200) [not null]
    state varchar(200)
    country varchar(2) [not null]
    start_date date [not null]
    end_date date
    description text [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'experiences_profile_id_idx']
        (account_id) [name: 'experiences_account_id_idx']
        (start_date) [name: 'experiences_start_date_idx']
    }
}
Ref: E.profile_id > P.id [delete: cascade]
Ref: E.account_id > A.id [delete: cascade]

Table educations as Ed {
    id serial [pk]

    school varchar(200) [not null]
    degree varchar(20) [not null]
    field_of_study varchar(200) [not null]
    start_date date [not null]
    end_date date
    description text [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'educations_profile_id_idx']
        (account_id) [name: 'educations_account_id_idx']
        (start_date) [name: 'educations_start_date_idx']
    }
}
Ref: Ed.profile_id > P.id [delete: cascade]
Ref: Ed.account_id > A.id [delete: cascade]

Table programming_languages as PL {
    id serial [pk]

    name varchar(50) [not null]
    icon text [not null]
    years_of_experience integer [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'programming_languages_profile_id_idx']
        (account_id) [name: 'programming_languages_account_id_idx']
        (name) [unique, name: 'programming_languages_name_uidx']
        (years_of_experience) [name: 'programming_languages_years_of_experience_idx']
    }
}
Ref: PL.profile_id > P.id [delete: cascade]
Ref: PL.account_id > A.id [delete: cascade]

Table frameworks_technologies as F {
    id serial [pk]

    name varchar(50) [not null]
    icon text [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'frameworks_profile_id_idx']
        (account_id) [name: 'frameworks_account_id_idx']
        (name) [unique, name: 'frameworks_name_uidx']
    }
}
Ref: F.profile_id > P.id [delete: cascade]
Ref: F.account_id > A.id [delete: cascade]

Table tools as T {
    id serial [pk]

    name varchar(50) [not null]
    category varchar(50) [not null]
    icon text [not null]

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'tools_profile_id_idx']
        (account_id) [name: 'tools_account_id_idx']
        (name) [unique, name: 'tools_name_uidx']
    }
}
Ref: T.profile_id > P.id [delete: cascade]
Ref: T.account_id > A.id [delete: cascade]

Table projects as Pr {
    id serial [pk]

    name varchar(200) [not null]
    description text [not null]
    start_date date [not null]
    end_date date

    profile_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (profile_id) [name: 'projects_profile_id_idx']
        (account_id) [name: 'projects_account_id_idx']
        (start_date) [name: 'projects_start_date_idx']
    }
}
Ref: Pr.profile_id > P.id [delete: cascade]
Ref: Pr.account_id > A.id [delete: cascade]

Table project_links as PL {
    id serial [pk]

    name varchar(200) [not null]
    url text [not null]

    project_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (project_id) [name: 'project_links_project_id_idx']
        (account_id) [name: 'project_links_account_id_idx']
        (project_id, url) [unique, name: 'project_links_project_id_url_uidx']
    }
}

Table project_programming_languages as PPL {
    project_id integer [not null]
    programming_language_id integer [not null]

    created_at timestamp [not null, default: `now()`]

    Indexes {
        (project_id, programming_language_id) [pk]
    }
}
Ref: PPL.project_id > Pr.id [delete: cascade]
Ref: PPL.programming_language_id > PL.id [delete: cascade]

Table project_frameworks_technologies as PFT {
    project_id integer [not null]
    framework_technology_id integer [not null]

    created_at timestamp [not null, default: `now()`]

    Indexes {
        (project_id, framework_technology_id) [pk]
    }
}
Ref: PFT.project_id > Pr.id [delete: cascade]
Ref: PFT.framework_technology_id > F.id [delete: cascade]

Table project_tools as PT {
    project_id integer [not null]
    tool_id integer [not null]

    created_at timestamp [not null, default: `now()`]

    Indexes {
        (project_id, tool_id) [pk]
    }
}
Ref: PT.project_id > Pr.id [delete: cascade]
Ref: PT.tool_id > T.id [delete: cascade]

Table project_images as PI {
    id uuid [pk]
    ext varchar(10) [not null]

    project_id integer [not null]
    account_id integer [not null]

    created_at timestamp [not null, default: `now()`]
    updated_at timestamp [not null, default: `now()`]

    Indexes {
        (project_id) [unique, name: 'project_images_project_id_uidx']
        (account_id) [unique, name: 'project_images_account_id_uidx']
    }
}
Ref: PI.project_id > Pr.id [delete: cascade]
Ref: PI.account_id > A.id [delete: cascade]

// Todo add blog post, comments, reactions, tags, series and images
