// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_dynamic_registration_domain_codes.sql

package database

import (
	"context"
	"time"
)

const createAccountDynamicRegistrationDomainCode = `-- name: CreateAccountDynamicRegistrationDomainCode :exec

INSERT INTO "account_dynamic_registration_domain_codes" (
    "account_id",
    "account_dynamic_registration_domain_id",
    "verification_host",
    "verification_code",
    "verification_prefix",
    "hmac_secret_id",
    "expires_at"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateAccountDynamicRegistrationDomainCodeParams struct {
	AccountID                          int32
	AccountDynamicRegistrationDomainID int32
	VerificationHost                   string
	VerificationCode                   string
	VerificationPrefix                 string
	HmacSecretID                       string
	ExpiresAt                          time.Time
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAccountDynamicRegistrationDomainCode(ctx context.Context, arg CreateAccountDynamicRegistrationDomainCodeParams) error {
	_, err := q.db.Exec(ctx, createAccountDynamicRegistrationDomainCode,
		arg.AccountID,
		arg.AccountDynamicRegistrationDomainID,
		arg.VerificationHost,
		arg.VerificationCode,
		arg.VerificationPrefix,
		arg.HmacSecretID,
		arg.ExpiresAt,
	)
	return err
}
