// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account_credentials.sql

package database

import (
	"context"
)

const countAccountCredentialsByAccountID = `-- name: CountAccountCredentialsByAccountID :one
SELECT COUNT("id") FROM "account_credentials"
WHERE "account_id" = $1
LIMIT 1
`

func (q *Queries) CountAccountCredentialsByAccountID(ctx context.Context, accountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountCredentialsByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountCredentials = `-- name: CreateAccountCredentials :one
INSERT INTO "account_credentials" (
    "client_id",
    "client_secret",
    "account_id",
    "scopes"
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, account_id, scopes, client_id, client_secret, created_at, updated_at
`

type CreateAccountCredentialsParams struct {
	ClientID     string
	ClientSecret string
	AccountID    int32
	Scopes       []byte
}

func (q *Queries) CreateAccountCredentials(ctx context.Context, arg CreateAccountCredentialsParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, createAccountCredentials,
		arg.ClientID,
		arg.ClientSecret,
		arg.AccountID,
		arg.Scopes,
	)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountCredentials = `-- name: DeleteAccountCredentials :exec
DELETE FROM "account_credentials"
WHERE "client_id" = $1
`

func (q *Queries) DeleteAccountCredentials(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, deleteAccountCredentials, clientID)
	return err
}

const findAccountCredentialsByClientID = `-- name: FindAccountCredentialsByClientID :one
SELECT id, account_id, scopes, client_id, client_secret, created_at, updated_at FROM "account_credentials"
WHERE "client_id" = $1
LIMIT 1
`

func (q *Queries) FindAccountCredentialsByClientID(ctx context.Context, clientID string) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, findAccountCredentialsByClientID, clientID)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPaginatedAccountCredentialsByAccountID = `-- name: FindPaginatedAccountCredentialsByAccountID :many
SELECT id, account_id, scopes, client_id, client_secret, created_at, updated_at FROM "account_credentials"
WHERE "account_id" = $1
ORDER BY "id" DESC
OFFSET $2 LIMIT $3
`

type FindPaginatedAccountCredentialsByAccountIDParams struct {
	AccountID int32
	Offset    int32
	Limit     int32
}

func (q *Queries) FindPaginatedAccountCredentialsByAccountID(ctx context.Context, arg FindPaginatedAccountCredentialsByAccountIDParams) ([]AccountCredential, error) {
	rows, err := q.db.Query(ctx, findPaginatedAccountCredentialsByAccountID, arg.AccountID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountCredential{}
	for rows.Next() {
		var i AccountCredential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Scopes,
			&i.ClientID,
			&i.ClientSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountCredentialsClientSecret = `-- name: UpdateAccountCredentialsClientSecret :one
UPDATE "account_credentials" SET
    "client_secret" = $1,
    "updated_at" = now()
WHERE "client_id" = $2
RETURNING id, account_id, scopes, client_id, client_secret, created_at, updated_at
`

type UpdateAccountCredentialsClientSecretParams struct {
	ClientSecret string
	ClientID     string
}

func (q *Queries) UpdateAccountCredentialsClientSecret(ctx context.Context, arg UpdateAccountCredentialsClientSecretParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, updateAccountCredentialsClientSecret, arg.ClientSecret, arg.ClientID)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountCredentialsScope = `-- name: UpdateAccountCredentialsScope :one
UPDATE "account_credentials" SET
    "scopes" = $1,
    "updated_at" = now()
WHERE "client_id" = $2
RETURNING id, account_id, scopes, client_id, client_secret, created_at, updated_at
`

type UpdateAccountCredentialsScopeParams struct {
	Scopes   []byte
	ClientID string
}

func (q *Queries) UpdateAccountCredentialsScope(ctx context.Context, arg UpdateAccountCredentialsScopeParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, updateAccountCredentialsScope, arg.Scopes, arg.ClientID)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
