// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_credentials.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountCredentialsByAccountPublicID = `-- name: CountAccountCredentialsByAccountPublicID :one
SELECT COUNT(*) FROM "account_credentials"
WHERE "account_public_id" = $1
LIMIT 1
`

func (q *Queries) CountAccountCredentialsByAccountPublicID(ctx context.Context, accountPublicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountCredentialsByAccountPublicID, accountPublicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountCredentialsByAccountPublicIDAndClientID = `-- name: CountAccountCredentialsByAccountPublicIDAndClientID :one
SELECT COUNT(*) FROM "account_credentials"
WHERE "account_public_id" = $1 AND "client_id" = $2
LIMIT 1
`

type CountAccountCredentialsByAccountPublicIDAndClientIDParams struct {
	AccountPublicID uuid.UUID
	ClientID        string
}

func (q *Queries) CountAccountCredentialsByAccountPublicIDAndClientID(ctx context.Context, arg CountAccountCredentialsByAccountPublicIDAndClientIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountCredentialsByAccountPublicIDAndClientID, arg.AccountPublicID, arg.ClientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountCredentialsByNameAndAccountID = `-- name: CountAccountCredentialsByNameAndAccountID :one
SELECT COUNT(*) FROM "account_credentials"
WHERE "account_id" = $1 AND "client_name" = $2
`

type CountAccountCredentialsByNameAndAccountIDParams struct {
	AccountID  int32
	ClientName string
}

func (q *Queries) CountAccountCredentialsByNameAndAccountID(ctx context.Context, arg CountAccountCredentialsByNameAndAccountIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountCredentialsByNameAndAccountID, arg.AccountID, arg.ClientName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountCredentials = `-- name: CreateAccountCredentials :one
INSERT INTO "account_credentials" (
    "account_id",
    "account_public_id",
    "domain",
    "creation_method",
    "client_id",
    "redirect_uris",
    "token_endpoint_auth_method",
    "grant_types",
    "response_types",
    "client_name",
    "client_uri",
    "logo_uri",
    "scopes",
    "contacts",
    "tos_uri",
    "policy_uri",
    "jwks_uri",
    "jwks",
    "software_id",
    "software_version",
    "credentials_type",
    "sector_identifier_uri",
    "subject_type",
    "id_token_signed_response_alg",
    "id_token_encrypted_response_alg",
    "id_token_encrypted_response_enc",
    "userinfo_signed_response_alg",
    "userinfo_encrypted_response_alg",
    "userinfo_encrypted_response_enc",
    "request_object_signing_alg",
    "request_object_encryption_alg",
    "request_object_encryption_enc",
    "token_endpoint_auth_signing_alg",
    "default_max_age",
    "require_auth_time",
    "default_acr_values",
    "initiate_login_uri",
    "request_uris",
    "access_token_signing_alg"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39
) RETURNING registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at
`

type CreateAccountCredentialsParams struct {
	AccountID                    int32
	AccountPublicID              uuid.UUID
	Domain                       string
	CreationMethod               CreationMethod
	ClientID                     string
	RedirectUris                 []string
	TokenEndpointAuthMethod      AuthMethod
	GrantTypes                   []GrantType
	ResponseTypes                []ResponseType
	ClientName                   string
	ClientUri                    string
	LogoUri                      pgtype.Text
	Scopes                       []AccountCredentialsScope
	Contacts                     []string
	TosUri                       pgtype.Text
	PolicyUri                    pgtype.Text
	JwksUri                      pgtype.Text
	Jwks                         []byte
	SoftwareID                   pgtype.Text
	SoftwareVersion              pgtype.Text
	CredentialsType              AccountCredentialsType
	SectorIdentifierUri          pgtype.Text
	SubjectType                  NullClientSubjectType
	IDTokenSignedResponseAlg     TokenCryptoSuite
	IDTokenEncryptedResponseAlg  NullTokenEncryptionAlgorithm
	IDTokenEncryptedResponseEnc  NullTokenEncryptionEncoding
	UserinfoSignedResponseAlg    NullTokenCryptoSuite
	UserinfoEncryptedResponseAlg NullTokenEncryptionAlgorithm
	UserinfoEncryptedResponseEnc NullTokenEncryptionEncoding
	RequestObjectSigningAlg      NullTokenCryptoSuite
	RequestObjectEncryptionAlg   NullTokenEncryptionAlgorithm
	RequestObjectEncryptionEnc   NullTokenEncryptionEncoding
	TokenEndpointAuthSigningAlg  NullTokenCryptoSuite
	DefaultMaxAge                pgtype.Int8
	RequireAuthTime              bool
	DefaultAcrValues             []string
	InitiateLoginUri             pgtype.Text
	RequestUris                  []string
	AccessTokenSigningAlg        TokenCryptoSuite
}

func (q *Queries) CreateAccountCredentials(ctx context.Context, arg CreateAccountCredentialsParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, createAccountCredentials,
		arg.AccountID,
		arg.AccountPublicID,
		arg.Domain,
		arg.CreationMethod,
		arg.ClientID,
		arg.RedirectUris,
		arg.TokenEndpointAuthMethod,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.ClientName,
		arg.ClientUri,
		arg.LogoUri,
		arg.Scopes,
		arg.Contacts,
		arg.TosUri,
		arg.PolicyUri,
		arg.JwksUri,
		arg.Jwks,
		arg.SoftwareID,
		arg.SoftwareVersion,
		arg.CredentialsType,
		arg.SectorIdentifierUri,
		arg.SubjectType,
		arg.IDTokenSignedResponseAlg,
		arg.IDTokenEncryptedResponseAlg,
		arg.IDTokenEncryptedResponseEnc,
		arg.UserinfoSignedResponseAlg,
		arg.UserinfoEncryptedResponseAlg,
		arg.UserinfoEncryptedResponseEnc,
		arg.RequestObjectSigningAlg,
		arg.RequestObjectEncryptionAlg,
		arg.RequestObjectEncryptionEnc,
		arg.TokenEndpointAuthSigningAlg,
		arg.DefaultMaxAge,
		arg.RequireAuthTime,
		arg.DefaultAcrValues,
		arg.InitiateLoginUri,
		arg.RequestUris,
		arg.AccessTokenSigningAlg,
	)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountCredentials = `-- name: DeleteAccountCredentials :exec
DELETE FROM "account_credentials"
WHERE "client_id" = $1
`

func (q *Queries) DeleteAccountCredentials(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, deleteAccountCredentials, clientID)
	return err
}

const deleteAllAccountCredentials = `-- name: DeleteAllAccountCredentials :exec
DELETE FROM "account_credentials"
`

func (q *Queries) DeleteAllAccountCredentials(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAccountCredentials)
	return err
}

const deleteRegisteredAccountCredentialsGrants = `-- name: DeleteRegisteredAccountCredentialsGrants :exec
DELETE FROM grants WHERE account_id = $1 AND granted_client_id = $2
`

type DeleteRegisteredAccountCredentialsGrantsParams struct {
	AccountID       int32
	GrantedClientID string
}

func (q *Queries) DeleteRegisteredAccountCredentialsGrants(ctx context.Context, arg DeleteRegisteredAccountCredentialsGrantsParams) error {
	_, err := q.db.Exec(ctx, deleteRegisteredAccountCredentialsGrants, arg.AccountID, arg.GrantedClientID)
	return err
}

const findAccountCredentialsByAccountPublicIDAndClientID = `-- name: FindAccountCredentialsByAccountPublicIDAndClientID :one
SELECT registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at FROM "account_credentials"
WHERE "account_public_id" = $1 AND "client_id" = $2
LIMIT 1
`

type FindAccountCredentialsByAccountPublicIDAndClientIDParams struct {
	AccountPublicID uuid.UUID
	ClientID        string
}

func (q *Queries) FindAccountCredentialsByAccountPublicIDAndClientID(ctx context.Context, arg FindAccountCredentialsByAccountPublicIDAndClientIDParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, findAccountCredentialsByAccountPublicIDAndClientID, arg.AccountPublicID, arg.ClientID)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountCredentialsByClientID = `-- name: FindAccountCredentialsByClientID :one

SELECT registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at FROM "account_credentials"
WHERE "client_id" = $1
LIMIT 1
`

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) FindAccountCredentialsByClientID(ctx context.Context, clientID string) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, findAccountCredentialsByClientID, clientID)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPaginatedAccountCredentialsByAccountPublicID = `-- name: FindPaginatedAccountCredentialsByAccountPublicID :many
SELECT registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at FROM "account_credentials"
WHERE "account_public_id" = $1
ORDER BY "id" DESC
OFFSET $2 LIMIT $3
`

type FindPaginatedAccountCredentialsByAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Offset          int32
	Limit           int32
}

func (q *Queries) FindPaginatedAccountCredentialsByAccountPublicID(ctx context.Context, arg FindPaginatedAccountCredentialsByAccountPublicIDParams) ([]AccountCredential, error) {
	rows, err := q.db.Query(ctx, findPaginatedAccountCredentialsByAccountPublicID, arg.AccountPublicID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountCredential{}
	for rows.Next() {
		var i AccountCredential
		if err := rows.Scan(
			&i.RegistrationTokenJti,
			&i.SoftwareStatement,
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.Domain,
			&i.CreationMethod,
			&i.Version,
			&i.ClientID,
			&i.RedirectUris,
			&i.TokenEndpointAuthMethod,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.ClientName,
			&i.ClientUri,
			&i.LogoUri,
			&i.Scopes,
			&i.Contacts,
			&i.TosUri,
			&i.PolicyUri,
			&i.JwksUri,
			&i.Jwks,
			&i.SoftwareID,
			&i.SoftwareVersion,
			&i.CredentialsType,
			&i.SectorIdentifierUri,
			&i.SubjectType,
			&i.IDTokenSignedResponseAlg,
			&i.IDTokenEncryptedResponseAlg,
			&i.IDTokenEncryptedResponseEnc,
			&i.UserinfoSignedResponseAlg,
			&i.UserinfoEncryptedResponseAlg,
			&i.UserinfoEncryptedResponseEnc,
			&i.RequestObjectSigningAlg,
			&i.RequestObjectEncryptionAlg,
			&i.RequestObjectEncryptionEnc,
			&i.TokenEndpointAuthSigningAlg,
			&i.DefaultMaxAge,
			&i.RequireAuthTime,
			&i.DefaultAcrValues,
			&i.InitiateLoginUri,
			&i.RequestUris,
			&i.AccessTokenSigningAlg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRegisteredAccountCredentials = `-- name: LockRegisteredAccountCredentials :one
SELECT registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at FROM account_credentials WHERE client_id = $1 AND account_public_id = $2 FOR UPDATE
`

type LockRegisteredAccountCredentialsParams struct {
	ClientID        string
	AccountPublicID uuid.UUID
}

func (q *Queries) LockRegisteredAccountCredentials(ctx context.Context, arg LockRegisteredAccountCredentialsParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, lockRegisteredAccountCredentials, arg.ClientID, arg.AccountPublicID)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRegisteredAccountCredentialsKeys = `-- name: RevokeRegisteredAccountCredentialsKeys :exec
UPDATE credentials_keys SET is_revoked = true, updated_at = now()
WHERE id IN (SELECT credentials_key_id FROM account_credentials_keys WHERE account_credentials_id = $1)
`

func (q *Queries) RevokeRegisteredAccountCredentialsKeys(ctx context.Context, accountCredentialsID int32) error {
	_, err := q.db.Exec(ctx, revokeRegisteredAccountCredentialsKeys, accountCredentialsID)
	return err
}

const revokeRegisteredAccountCredentialsSecrets = `-- name: RevokeRegisteredAccountCredentialsSecrets :exec
UPDATE credentials_secrets SET is_revoked = true, updated_at = now()
WHERE id IN (SELECT credentials_secret_id FROM account_credentials_secrets WHERE account_credentials_id = $1)
`

func (q *Queries) RevokeRegisteredAccountCredentialsSecrets(ctx context.Context, accountCredentialsID int32) error {
	_, err := q.db.Exec(ctx, revokeRegisteredAccountCredentialsSecrets, accountCredentialsID)
	return err
}

const setAccountCredentialsRegistrationState = `-- name: SetAccountCredentialsRegistrationState :exec
UPDATE account_credentials SET registration_token_jti = $2, software_statement = $3 WHERE id = $1
`

type SetAccountCredentialsRegistrationStateParams struct {
	ID                   int32
	RegistrationTokenJti pgtype.UUID
	SoftwareStatement    string
}

func (q *Queries) SetAccountCredentialsRegistrationState(ctx context.Context, arg SetAccountCredentialsRegistrationStateParams) error {
	_, err := q.db.Exec(ctx, setAccountCredentialsRegistrationState, arg.ID, arg.RegistrationTokenJti, arg.SoftwareStatement)
	return err
}

const updateAccountCredentials = `-- name: UpdateAccountCredentials :one
UPDATE "account_credentials" SET
    "scopes" = $2,
    "client_name" = $3,
    "domain" = $4,
    "client_uri" = $5,
    "redirect_uris" = $6,
    "logo_uri" = $7,
    "policy_uri" = $8,
    "tos_uri" = $9,
    "software_version" = $10,
    "contacts" = $11,
    "version" = "version" + 1,
    "updated_at" = now()
WHERE "id" = $1
RETURNING registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at
`

type UpdateAccountCredentialsParams struct {
	ID              int32
	Scopes          []AccountCredentialsScope
	ClientName      string
	Domain          string
	ClientUri       string
	RedirectUris    []string
	LogoUri         pgtype.Text
	PolicyUri       pgtype.Text
	TosUri          pgtype.Text
	SoftwareVersion pgtype.Text
	Contacts        []string
}

func (q *Queries) UpdateAccountCredentials(ctx context.Context, arg UpdateAccountCredentialsParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, updateAccountCredentials,
		arg.ID,
		arg.Scopes,
		arg.ClientName,
		arg.Domain,
		arg.ClientUri,
		arg.RedirectUris,
		arg.LogoUri,
		arg.PolicyUri,
		arg.TosUri,
		arg.SoftwareVersion,
		arg.Contacts,
	)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegisteredAccountCredentials = `-- name: UpdateRegisteredAccountCredentials :one
UPDATE "account_credentials" SET
    "domain" = $2,
    "redirect_uris" = $3,
    "token_endpoint_auth_method" = $4,
    "grant_types" = $5,
    "response_types" = $6,
    "client_name" = $7,
    "client_uri" = $8,
    "logo_uri" = $9,
    "scopes" = $10,
    "contacts" = $11,
    "tos_uri" = $12,
    "policy_uri" = $13,
    "jwks_uri" = $14,
    "jwks" = $15,
    "software_id" = $16,
    "software_version" = $17,
    "sector_identifier_uri" = $18,
    "subject_type" = $19,
    "id_token_signed_response_alg" = $20,
    "id_token_encrypted_response_alg" = $21,
    "id_token_encrypted_response_enc" = $22,
    "userinfo_signed_response_alg" = $23,
    "userinfo_encrypted_response_alg" = $24,
    "userinfo_encrypted_response_enc" = $25,
    "request_object_signing_alg" = $26,
    "request_object_encryption_alg" = $27,
    "request_object_encryption_enc" = $28,
    "token_endpoint_auth_signing_alg" = $29,
    "default_max_age" = $30,
    "require_auth_time" = $31,
    "default_acr_values" = $32,
    "initiate_login_uri" = $33,
    "request_uris" = $34,
    "access_token_signing_alg" = $35,
    "version" = "version" + 1,
    "updated_at" = now()
WHERE "id" = $1
RETURNING registration_token_jti, software_statement, id, account_id, account_public_id, domain, creation_method, version, client_id, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, credentials_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, created_at, updated_at
`

type UpdateRegisteredAccountCredentialsParams struct {
	ID                           int32
	Domain                       string
	RedirectUris                 []string
	TokenEndpointAuthMethod      AuthMethod
	GrantTypes                   []GrantType
	ResponseTypes                []ResponseType
	ClientName                   string
	ClientUri                    string
	LogoUri                      pgtype.Text
	Scopes                       []AccountCredentialsScope
	Contacts                     []string
	TosUri                       pgtype.Text
	PolicyUri                    pgtype.Text
	JwksUri                      pgtype.Text
	Jwks                         []byte
	SoftwareID                   pgtype.Text
	SoftwareVersion              pgtype.Text
	SectorIdentifierUri          pgtype.Text
	SubjectType                  NullClientSubjectType
	IDTokenSignedResponseAlg     TokenCryptoSuite
	IDTokenEncryptedResponseAlg  NullTokenEncryptionAlgorithm
	IDTokenEncryptedResponseEnc  NullTokenEncryptionEncoding
	UserinfoSignedResponseAlg    NullTokenCryptoSuite
	UserinfoEncryptedResponseAlg NullTokenEncryptionAlgorithm
	UserinfoEncryptedResponseEnc NullTokenEncryptionEncoding
	RequestObjectSigningAlg      NullTokenCryptoSuite
	RequestObjectEncryptionAlg   NullTokenEncryptionAlgorithm
	RequestObjectEncryptionEnc   NullTokenEncryptionEncoding
	TokenEndpointAuthSigningAlg  NullTokenCryptoSuite
	DefaultMaxAge                pgtype.Int8
	RequireAuthTime              bool
	DefaultAcrValues             []string
	InitiateLoginUri             pgtype.Text
	RequestUris                  []string
	AccessTokenSigningAlg        TokenCryptoSuite
}

func (q *Queries) UpdateRegisteredAccountCredentials(ctx context.Context, arg UpdateRegisteredAccountCredentialsParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, updateRegisteredAccountCredentials,
		arg.ID,
		arg.Domain,
		arg.RedirectUris,
		arg.TokenEndpointAuthMethod,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.ClientName,
		arg.ClientUri,
		arg.LogoUri,
		arg.Scopes,
		arg.Contacts,
		arg.TosUri,
		arg.PolicyUri,
		arg.JwksUri,
		arg.Jwks,
		arg.SoftwareID,
		arg.SoftwareVersion,
		arg.SectorIdentifierUri,
		arg.SubjectType,
		arg.IDTokenSignedResponseAlg,
		arg.IDTokenEncryptedResponseAlg,
		arg.IDTokenEncryptedResponseEnc,
		arg.UserinfoSignedResponseAlg,
		arg.UserinfoEncryptedResponseAlg,
		arg.UserinfoEncryptedResponseEnc,
		arg.RequestObjectSigningAlg,
		arg.RequestObjectEncryptionAlg,
		arg.RequestObjectEncryptionEnc,
		arg.TokenEndpointAuthSigningAlg,
		arg.DefaultMaxAge,
		arg.RequireAuthTime,
		arg.DefaultAcrValues,
		arg.InitiateLoginUri,
		arg.RequestUris,
		arg.AccessTokenSigningAlg,
	)
	var i AccountCredential
	err := row.Scan(
		&i.RegistrationTokenJti,
		&i.SoftwareStatement,
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.CreationMethod,
		&i.Version,
		&i.ClientID,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.CredentialsType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
