// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account_recovery_keys.sql

package database

import (
	"context"
)

const createAccountRecoveryKeys = `-- name: CreateAccountRecoveryKeys :exec
INSERT INTO "account_recovery_keys" (
  "account_id",
  "keys"
) VALUES (
  $1,
  $2
)
`

type CreateAccountRecoveryKeysParams struct {
	AccountID int32
	Keys      []byte
}

func (q *Queries) CreateAccountRecoveryKeys(ctx context.Context, arg CreateAccountRecoveryKeysParams) error {
	_, err := q.db.Exec(ctx, createAccountRecoveryKeys, arg.AccountID, arg.Keys)
	return err
}

const deleteAccountRecoveryKeys = `-- name: DeleteAccountRecoveryKeys :exec
DELETE FROM "account_recovery_keys"
WHERE "account_id" = $1
`

func (q *Queries) DeleteAccountRecoveryKeys(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteAccountRecoveryKeys, accountID)
	return err
}
