// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountSessionWithAccountCredentials = `-- name: CreateAccountSessionWithAccountCredentials :exec
INSERT INTO "account_sessions" (
  "account_id",
  "account_version",
  "session_id",
  "session_uuid",
  "account_credentials_id"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
`

type CreateAccountSessionWithAccountCredentialsParams struct {
	AccountID            int32
	AccountVersion       int32
	SessionID            int32
	SessionUuid          uuid.UUID
	AccountCredentialsID pgtype.Int4
}

func (q *Queries) CreateAccountSessionWithAccountCredentials(ctx context.Context, arg CreateAccountSessionWithAccountCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAccountSessionWithAccountCredentials,
		arg.AccountID,
		arg.AccountVersion,
		arg.SessionID,
		arg.SessionUuid,
		arg.AccountCredentialsID,
	)
	return err
}

const createAccountSessionWithoutAccountCredentials = `-- name: CreateAccountSessionWithoutAccountCredentials :exec

INSERT INTO "account_sessions" (
  "account_id",
  "account_version",
  "session_id",
  "session_uuid"
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateAccountSessionWithoutAccountCredentialsParams struct {
	AccountID      int32
	AccountVersion int32
	SessionID      int32
	SessionUuid    uuid.UUID
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAccountSessionWithoutAccountCredentials(ctx context.Context, arg CreateAccountSessionWithoutAccountCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAccountSessionWithoutAccountCredentials,
		arg.AccountID,
		arg.AccountVersion,
		arg.SessionID,
		arg.SessionUuid,
	)
	return err
}

const deleteAccountSessionByAccountIDAndSessionID = `-- name: DeleteAccountSessionByAccountIDAndSessionID :exec
DELETE FROM "account_sessions"
WHERE "account_id" = $1 AND "session_id" = $2
`

type DeleteAccountSessionByAccountIDAndSessionIDParams struct {
	AccountID int32
	SessionID int32
}

func (q *Queries) DeleteAccountSessionByAccountIDAndSessionID(ctx context.Context, arg DeleteAccountSessionByAccountIDAndSessionIDParams) error {
	_, err := q.db.Exec(ctx, deleteAccountSessionByAccountIDAndSessionID, arg.AccountID, arg.SessionID)
	return err
}

const deleteAllSessionsByAccountID = `-- name: DeleteAllSessionsByAccountID :exec
DELETE FROM "sessions" AS "s"
USING "account_sessions" AS "a"
WHERE "a"."session_id" = "s"."id"
AND "a"."account_id" = $1
`

func (q *Queries) DeleteAllSessionsByAccountID(ctx context.Context, accountID int32) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByAccountID, accountID)
	return err
}

const findAccountSessionByAccountIDAndSessionUUID = `-- name: FindAccountSessionByAccountIDAndSessionUUID :one
SELECT a.account_id, a.account_version, a.session_id, a.account_credentials_id, a.session_uuid, a.created_at, s.id, s.account_id, s.grant_id, s.session_id, s.session_type, s.session_client_id, s.ip_address, s.user_agent, s.issued_at, s.expires_at, s.created_at, s.updated_at
FROM "account_sessions" AS "a"
LEFT JOIN "sessions" AS "s" ON "a"."session_id" = "s"."id"
WHERE "a"."account_id" = $1
AND "a"."session_uuid" = $2
LIMIT 1
`

type FindAccountSessionByAccountIDAndSessionUUIDParams struct {
	AccountID   int32
	SessionUuid uuid.UUID
}

type FindAccountSessionByAccountIDAndSessionUUIDRow struct {
	AccountID            int32
	AccountVersion       int32
	SessionID            int32
	AccountCredentialsID pgtype.Int4
	SessionUuid          uuid.UUID
	CreatedAt            time.Time
	ID                   pgtype.Int4
	AccountID_2          pgtype.Int4
	GrantID              pgtype.Int4
	SessionID_2          pgtype.UUID
	SessionType          NullSessionType
	SessionClientID      pgtype.Text
	IpAddress            pgtype.Text
	UserAgent            pgtype.Text
	IssuedAt             pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	CreatedAt_2          pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindAccountSessionByAccountIDAndSessionUUID(ctx context.Context, arg FindAccountSessionByAccountIDAndSessionUUIDParams) (FindAccountSessionByAccountIDAndSessionUUIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountSessionByAccountIDAndSessionUUID, arg.AccountID, arg.SessionUuid)
	var i FindAccountSessionByAccountIDAndSessionUUIDRow
	err := row.Scan(
		&i.AccountID,
		&i.AccountVersion,
		&i.SessionID,
		&i.AccountCredentialsID,
		&i.SessionUuid,
		&i.CreatedAt,
		&i.ID,
		&i.AccountID_2,
		&i.GrantID,
		&i.SessionID_2,
		&i.SessionType,
		&i.SessionClientID,
		&i.IpAddress,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.UpdatedAt,
	)
	return i, err
}
