// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_2fa_configs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countAccount2FAConfigsByAccountID = `-- name: CountAccount2FAConfigsByAccountID :one
SELECT COUNT(*) FROM "account_2fa_configs"
WHERE "account_id" = $1
LIMIT 1
`

func (q *Queries) CountAccount2FAConfigsByAccountID(ctx context.Context, accountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAccount2FAConfigsByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount2FAConfig = `-- name: CreateAccount2FAConfig :one

INSERT INTO "account_2fa_configs" (
    "account_id",
    "account_public_id",
    "two_factor_type",
    "is_default"
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, account_id, account_public_id, two_factor_type, is_default, is_active, created_at, updated_at
`

type CreateAccount2FAConfigParams struct {
	AccountID       int32
	AccountPublicID uuid.UUID
	TwoFactorType   TwoFactorType
	IsDefault       bool
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAccount2FAConfig(ctx context.Context, arg CreateAccount2FAConfigParams) (Account2faConfig, error) {
	row := q.db.QueryRow(ctx, createAccount2FAConfig,
		arg.AccountID,
		arg.AccountPublicID,
		arg.TwoFactorType,
		arg.IsDefault,
	)
	var i Account2faConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.TwoFactorType,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount2FAConfig = `-- name: DeleteAccount2FAConfig :exec
DELETE FROM "account_2fa_configs"
WHERE "id" = $1
`

func (q *Queries) DeleteAccount2FAConfig(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccount2FAConfig, id)
	return err
}

const findAccount2FAConfigByAccountPublicIDAndType = `-- name: FindAccount2FAConfigByAccountPublicIDAndType :one
SELECT id, account_id, account_public_id, two_factor_type, is_default, is_active, created_at, updated_at FROM "account_2fa_configs"
WHERE "account_public_id" = $1 AND "two_factor_type" = $2
LIMIT 1
`

type FindAccount2FAConfigByAccountPublicIDAndTypeParams struct {
	AccountPublicID uuid.UUID
	TwoFactorType   TwoFactorType
}

func (q *Queries) FindAccount2FAConfigByAccountPublicIDAndType(ctx context.Context, arg FindAccount2FAConfigByAccountPublicIDAndTypeParams) (Account2faConfig, error) {
	row := q.db.QueryRow(ctx, findAccount2FAConfigByAccountPublicIDAndType, arg.AccountPublicID, arg.TwoFactorType)
	var i Account2faConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.TwoFactorType,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccount2FAConfigsByAccountPublicID = `-- name: FindAccount2FAConfigsByAccountPublicID :many
SELECT id, account_id, account_public_id, two_factor_type, is_default, is_active, created_at, updated_at FROM "account_2fa_configs"
WHERE "account_public_id" = $1
ORDER BY "id" DESC
`

func (q *Queries) FindAccount2FAConfigsByAccountPublicID(ctx context.Context, accountPublicID uuid.UUID) ([]Account2faConfig, error) {
	rows, err := q.db.Query(ctx, findAccount2FAConfigsByAccountPublicID, accountPublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account2faConfig{}
	for rows.Next() {
		var i Account2faConfig
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.TwoFactorType,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDefaultAccount2FAConfigByAccountPublicID = `-- name: FindDefaultAccount2FAConfigByAccountPublicID :one
SELECT id, account_id, account_public_id, two_factor_type, is_default, is_active, created_at, updated_at FROM "account_2fa_configs"
WHERE "account_public_id" = $1 AND "is_default" = true 
LIMIT 1
`

func (q *Queries) FindDefaultAccount2FAConfigByAccountPublicID(ctx context.Context, accountPublicID uuid.UUID) (Account2faConfig, error) {
	row := q.db.QueryRow(ctx, findDefaultAccount2FAConfigByAccountPublicID, accountPublicID)
	var i Account2faConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.TwoFactorType,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount2FAConfig = `-- name: UpdateAccount2FAConfig :one
UPDATE "account_2fa_configs" SET
    "is_default" = $2,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, account_id, account_public_id, two_factor_type, is_default, is_active, created_at, updated_at
`

type UpdateAccount2FAConfigParams struct {
	ID        int32
	IsDefault bool
}

func (q *Queries) UpdateAccount2FAConfig(ctx context.Context, arg UpdateAccount2FAConfigParams) (Account2faConfig, error) {
	row := q.db.QueryRow(ctx, updateAccount2FAConfig, arg.ID, arg.IsDefault)
	var i Account2faConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.TwoFactorType,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
