// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_grants.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountGrantWithAccountCredentials = `-- name: CreateAccountGrantWithAccountCredentials :exec
INSERT INTO "account_grants" (
  "account_id",
  "account_version",
  "grant_id",
  "granted_client_id",
  "account_credentials_id"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
`

type CreateAccountGrantWithAccountCredentialsParams struct {
	AccountID            int32
	AccountVersion       int32
	GrantID              int32
	GrantedClientID      string
	AccountCredentialsID pgtype.Int4
}

func (q *Queries) CreateAccountGrantWithAccountCredentials(ctx context.Context, arg CreateAccountGrantWithAccountCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAccountGrantWithAccountCredentials,
		arg.AccountID,
		arg.AccountVersion,
		arg.GrantID,
		arg.GrantedClientID,
		arg.AccountCredentialsID,
	)
	return err
}

const createAccountGrantWithoutAccountCredentials = `-- name: CreateAccountGrantWithoutAccountCredentials :exec

INSERT INTO "account_grants" (
  "account_id",
  "account_version",
  "grant_id",
  "granted_client_id"
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreateAccountGrantWithoutAccountCredentialsParams struct {
	AccountID       int32
	AccountVersion  int32
	GrantID         int32
	GrantedClientID string
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAccountGrantWithoutAccountCredentials(ctx context.Context, arg CreateAccountGrantWithoutAccountCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAccountGrantWithoutAccountCredentials,
		arg.AccountID,
		arg.AccountVersion,
		arg.GrantID,
		arg.GrantedClientID,
	)
	return err
}

const findAccountGrantByAccountIDAndGrantedClientID = `-- name: FindAccountGrantByAccountIDAndGrantedClientID :one
SELECT a.account_id, a.account_version, a.grant_id, a.account_credentials_id, a.granted_client_id, a.is_revoked, a.revoked_at, a.expires_at, a.created_at, g.id, g.account_id, g.grant_id, g.granted_client_id, g.granted_scopes, g.granted_custom_scopes, g.issued_at, g.last_active_at, g.created_at, g.updated_at
FROM "account_grants" AS "a"
LEFT JOIN "grants" AS "g" ON "a"."grant_id" = "g"."id"
WHERE "a"."account_id" = $1
AND "a"."granted_client_id" = $2
LIMIT 1
`

type FindAccountGrantByAccountIDAndGrantedClientIDParams struct {
	AccountID       int32
	GrantedClientID string
}

type FindAccountGrantByAccountIDAndGrantedClientIDRow struct {
	AccountID            int32
	AccountVersion       int32
	GrantID              int32
	AccountCredentialsID pgtype.Int4
	GrantedClientID      string
	IsRevoked            bool
	RevokedAt            pgtype.Timestamptz
	ExpiresAt            pgtype.Timestamptz
	CreatedAt            time.Time
	ID                   pgtype.Int4
	AccountID_2          pgtype.Int4
	GrantID_2            pgtype.UUID
	GrantedClientID_2    pgtype.Text
	GrantedScopes        []Scopes
	GrantedCustomScopes  []string
	IssuedAt             pgtype.Timestamptz
	LastActiveAt         pgtype.Timestamptz
	CreatedAt_2          pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) FindAccountGrantByAccountIDAndGrantedClientID(ctx context.Context, arg FindAccountGrantByAccountIDAndGrantedClientIDParams) (FindAccountGrantByAccountIDAndGrantedClientIDRow, error) {
	row := q.db.QueryRow(ctx, findAccountGrantByAccountIDAndGrantedClientID, arg.AccountID, arg.GrantedClientID)
	var i FindAccountGrantByAccountIDAndGrantedClientIDRow
	err := row.Scan(
		&i.AccountID,
		&i.AccountVersion,
		&i.GrantID,
		&i.AccountCredentialsID,
		&i.GrantedClientID,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ID,
		&i.AccountID_2,
		&i.GrantID_2,
		&i.GrantedClientID_2,
		&i.GrantedScopes,
		&i.GrantedCustomScopes,
		&i.IssuedAt,
		&i.LastActiveAt,
		&i.CreatedAt_2,
		&i.UpdatedAt,
	)
	return i, err
}
