// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_service_configs.sql

package database

import (
	"context"
)

const createAppServiceConfig = `-- name: CreateAppServiceConfig :one

INSERT INTO "app_service_configs" (
    "account_id",
    "app_id",
    "auth_methods",
    "grant_types",
    "allowed_domains"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, account_id, app_id, auth_methods, grant_types, allowed_domains, created_at, updated_at
`

type CreateAppServiceConfigParams struct {
	AccountID      int32
	AppID          int32
	AuthMethods    []AuthMethod
	GrantTypes     []GrantType
	AllowedDomains []string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAppServiceConfig(ctx context.Context, arg CreateAppServiceConfigParams) (AppServiceConfig, error) {
	row := q.db.QueryRow(ctx, createAppServiceConfig,
		arg.AccountID,
		arg.AppID,
		arg.AuthMethods,
		arg.GrantTypes,
		arg.AllowedDomains,
	)
	var i AppServiceConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.AuthMethods,
		&i.GrantTypes,
		&i.AllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
