// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_profiles.sql

package database

import (
	"context"
)

const createAppProfile = `-- name: CreateAppProfile :exec
INSERT INTO "app_profiles" (
    "account_id",
    "user_id",
    "app_id"
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateAppProfileParams struct {
	AccountID int32
	UserID    int32
	AppID     int32
}

func (q *Queries) CreateAppProfile(ctx context.Context, arg CreateAppProfileParams) error {
	_, err := q.db.Exec(ctx, createAppProfile, arg.AccountID, arg.UserID, arg.AppID)
	return err
}

const findAppProfileIDByAppIDAndUserID = `-- name: FindAppProfileIDByAppIDAndUserID :one
SELECT "id" FROM "app_profiles"
WHERE "app_id" = $1 AND "user_id" = $2 LIMIT 1
`

type FindAppProfileIDByAppIDAndUserIDParams struct {
	AppID  int32
	UserID int32
}

func (q *Queries) FindAppProfileIDByAppIDAndUserID(ctx context.Context, arg FindAppProfileIDByAppIDAndUserIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, findAppProfileIDByAppIDAndUserID, arg.AppID, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
