// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_related_apps.sql

package database

import (
	"context"
)

const createAppRelatedApp = `-- name: CreateAppRelatedApp :exec

INSERT INTO "app_related_apps" (
    "app_id",
    "related_app_id",
    "account_id"
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateAppRelatedAppParams struct {
	AppID        int32
	RelatedAppID int32
	AccountID    int32
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAppRelatedApp(ctx context.Context, arg CreateAppRelatedAppParams) error {
	_, err := q.db.Exec(ctx, createAppRelatedApp, arg.AppID, arg.RelatedAppID, arg.AccountID)
	return err
}
