// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_profiles.sql

package database

import (
	"context"
)

const createAppProfileWithData = `-- name: CreateAppProfileWithData :exec
INSERT INTO "app_profiles" (
    "account_id",
    "user_id",
    "app_id",
    "profile_data"
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateAppProfileWithDataParams struct {
	AccountID   int32
	UserID      int32
	AppID       int32
	ProfileData []byte
}

func (q *Queries) CreateAppProfileWithData(ctx context.Context, arg CreateAppProfileWithDataParams) error {
	_, err := q.db.Exec(ctx, createAppProfileWithData,
		arg.AccountID,
		arg.UserID,
		arg.AppID,
		arg.ProfileData,
	)
	return err
}

const createAppProfileWithoutData = `-- name: CreateAppProfileWithoutData :exec
INSERT INTO "app_profiles" (
    "account_id",
    "user_id",
    "app_id"
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateAppProfileWithoutDataParams struct {
	AccountID int32
	UserID    int32
	AppID     int32
}

func (q *Queries) CreateAppProfileWithoutData(ctx context.Context, arg CreateAppProfileWithoutDataParams) error {
	_, err := q.db.Exec(ctx, createAppProfileWithoutData, arg.AccountID, arg.UserID, arg.AppID)
	return err
}

const findAppProfileByAppIDAndUserID = `-- name: FindAppProfileByAppIDAndUserID :one
SELECT id, account_id, user_id, app_id, user_roles, profile_data, created_at, updated_at FROM "app_profiles"
WHERE "app_id" = $1 AND "user_id" = $2 LIMIT 1
`

type FindAppProfileByAppIDAndUserIDParams struct {
	AppID  int32
	UserID int32
}

func (q *Queries) FindAppProfileByAppIDAndUserID(ctx context.Context, arg FindAppProfileByAppIDAndUserIDParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, findAppProfileByAppIDAndUserID, arg.AppID, arg.UserID)
	var i AppProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.AppID,
		&i.UserRoles,
		&i.ProfileData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
