// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: app_secrets.sql

package database

import (
	"context"
)

const createAppSecret = `-- name: CreateAppSecret :exec

INSERT INTO "app_secrets" (
    "app_id",
    "credentials_secret_id",
    "account_id"
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateAppSecretParams struct {
	AppID               int32
	CredentialsSecretID int32
	AccountID           int32
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAppSecret(ctx context.Context, arg CreateAppSecretParams) error {
	_, err := q.db.Exec(ctx, createAppSecret, arg.AppID, arg.CredentialsSecretID, arg.AccountID)
	return err
}
