// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_keys.sql

package database

import (
	"context"
)

const deleteDistributedAppKeysByAppID = `-- name: DeleteDistributedAppKeysByAppID :exec
DELETE FROM "app_keys"
WHERE "app_id" = $1 AND "is_distributed" = true
`

func (q *Queries) DeleteDistributedAppKeysByAppID(ctx context.Context, appID int32) error {
	_, err := q.db.Exec(ctx, deleteDistributedAppKeysByAppID, appID)
	return err
}
