// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: app_profiles.sql

package database

import (
	"context"
)

const createAppProfile = `-- name: CreateAppProfile :exec
INSERT INTO "app_profiles" (
    "account_id",
    "user_id",
    "app_id"
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateAppProfileParams struct {
	AccountID int32
	UserID    int32
	AppID     int32
}

func (q *Queries) CreateAppProfile(ctx context.Context, arg CreateAppProfileParams) error {
	_, err := q.db.Exec(ctx, createAppProfile, arg.AccountID, arg.UserID, arg.AppID)
	return err
}

const findAppProfileByAppIDAndUserID = `-- name: FindAppProfileByAppIDAndUserID :one
SELECT id, account_id, user_id, app_id, created_at, updated_at FROM "app_profiles"
WHERE "app_id" = $1 AND "user_id" = $2 LIMIT 1
`

type FindAppProfileByAppIDAndUserIDParams struct {
	AppID  int32
	UserID int32
}

func (q *Queries) FindAppProfileByAppIDAndUserID(ctx context.Context, arg FindAppProfileByAppIDAndUserIDParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, findAppProfileByAppIDAndUserID, arg.AppID, arg.UserID)
	var i AppProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.AppID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
