// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_server_configs.sql

package database

import (
	"context"
)

const createAppServerConfig = `-- name: CreateAppServerConfig :one

INSERT INTO "app_server_configs" (
    "account_id",
    "app_id",
    "confirmation_url",
    "reset_password_url"
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, account_id, app_id, confirmation_url, reset_password_url, created_at, updated_at
`

type CreateAppServerConfigParams struct {
	AccountID        int32
	AppID            int32
	ConfirmationUrl  string
	ResetPasswordUrl string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAppServerConfig(ctx context.Context, arg CreateAppServerConfigParams) (AppServerConfig, error) {
	row := q.db.QueryRow(ctx, createAppServerConfig,
		arg.AccountID,
		arg.AppID,
		arg.ConfirmationUrl,
		arg.ResetPasswordUrl,
	)
	var i AppServerConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.ConfirmationUrl,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
