// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: app_service_configs.sql

package database

import (
	"context"
)

const createAppServiceConfig = `-- name: CreateAppServiceConfig :one

INSERT INTO "app_service_configs" (
    "account_id",
    "app_id",
    "user_auth_method",
    "user_grant_types",
    "allowed_domains"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, account_id, app_id, user_auth_method, user_grant_types, allowed_domains, created_at, updated_at
`

type CreateAppServiceConfigParams struct {
	AccountID      int32
	AppID          int32
	UserAuthMethod AuthMethod
	UserGrantTypes []GrantType
	AllowedDomains []string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAppServiceConfig(ctx context.Context, arg CreateAppServiceConfigParams) (AppServiceConfig, error) {
	row := q.db.QueryRow(ctx, createAppServiceConfig,
		arg.AccountID,
		arg.AppID,
		arg.UserAuthMethod,
		arg.UserGrantTypes,
		arg.AllowedDomains,
	)
	var i AppServiceConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.UserAuthMethod,
		&i.UserGrantTypes,
		&i.AllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAppServiceConfig = `-- name: FindAppServiceConfig :one
SELECT id, account_id, app_id, user_auth_method, user_grant_types, allowed_domains, created_at, updated_at FROM "app_service_configs"
WHERE "app_id" = $1 LIMIT 1
`

func (q *Queries) FindAppServiceConfig(ctx context.Context, appID int32) (AppServiceConfig, error) {
	row := q.db.QueryRow(ctx, findAppServiceConfig, appID)
	var i AppServiceConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.UserAuthMethod,
		&i.UserGrantTypes,
		&i.AllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppServiceConfig = `-- name: UpdateAppServiceConfig :one
UPDATE "app_service_configs"
SET "allowed_domains" = $3,
    "updated_at" = now()
WHERE "account_id" = $1 AND "app_id" = $2
RETURNING id, account_id, app_id, user_auth_method, user_grant_types, allowed_domains, created_at, updated_at
`

type UpdateAppServiceConfigParams struct {
	AccountID      int32
	AppID          int32
	AllowedDomains []string
}

func (q *Queries) UpdateAppServiceConfig(ctx context.Context, arg UpdateAppServiceConfigParams) (AppServiceConfig, error) {
	row := q.db.QueryRow(ctx, updateAppServiceConfig, arg.AccountID, arg.AppID, arg.AllowedDomains)
	var i AppServiceConfig
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AppID,
		&i.UserAuthMethod,
		&i.UserGrantTypes,
		&i.AllowedDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
