// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package database

import (
	"context"
)

const countAppsByAccountID = `-- name: CountAppsByAccountID :one
SELECT COUNT("id") FROM "apps"
WHERE "account_id" = $1
LIMIT 1
`

func (q *Queries) CountAppsByAccountID(ctx context.Context, accountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAppsByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppsByNameAndAccountID = `-- name: CountAppsByNameAndAccountID :one
SELECT COUNT("id") FROM "apps"
WHERE "account_id" = $1 AND "name" = $2
LIMIT 1
`

type CountAppsByNameAndAccountIDParams struct {
	AccountID int32
	Name      string
}

func (q *Queries) CountAppsByNameAndAccountID(ctx context.Context, arg CountAppsByNameAndAccountIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAppsByNameAndAccountID, arg.AccountID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilteredAppsByNameAndByAccountID = `-- name: CountFilteredAppsByNameAndByAccountID :one
SELECT COUNT("id") FROM "apps"
WHERE "account_id" = $1 AND "name" ILIKE $2
LIMIT 1
`

type CountFilteredAppsByNameAndByAccountIDParams struct {
	AccountID int32
	Name      string
}

func (q *Queries) CountFilteredAppsByNameAndByAccountID(ctx context.Context, arg CountFilteredAppsByNameAndByAccountIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredAppsByNameAndByAccountID, arg.AccountID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :one

INSERT INTO "apps" (
  "account_id",
  "type",
  "name",
  "username_column",
  "client_id",
  "client_secret"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at
`

type CreateAppParams struct {
	AccountID      int32
	Type           string
	Name           string
	UsernameColumn string
	ClientID       string
	ClientSecret   string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.AccountID,
		arg.Type,
		arg.Name,
		arg.UsernameColumn,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.ConfirmationUri,
		&i.ResetUri,
		&i.CallbackUris,
		&i.LogoutUris,
		&i.DefaultScopes,
		&i.UserRoles,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.IDTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :exec
DELETE FROM "apps"
WHERE "id" = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}

const filterAppsByNameAndByAccountIDOrderedByID = `-- name: FilterAppsByNameAndByAccountIDOrderedByID :many
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "account_id" = $1 AND "name" ILIKE $2
ORDER BY "id" DESC
OFFSET $3 LIMIT $4
`

type FilterAppsByNameAndByAccountIDOrderedByIDParams struct {
	AccountID int32
	Name      string
	Offset    int32
	Limit     int32
}

func (q *Queries) FilterAppsByNameAndByAccountIDOrderedByID(ctx context.Context, arg FilterAppsByNameAndByAccountIDOrderedByIDParams) ([]App, error) {
	rows, err := q.db.Query(ctx, filterAppsByNameAndByAccountIDOrderedByID,
		arg.AccountID,
		arg.Name,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Name,
			&i.ClientID,
			&i.ClientSecret,
			&i.ConfirmationUri,
			&i.ResetUri,
			&i.CallbackUris,
			&i.LogoutUris,
			&i.DefaultScopes,
			&i.UserRoles,
			&i.AuthProviders,
			&i.UsernameColumn,
			&i.IDTokenTtl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterAppsByNameAndByAccountIDOrderedByName = `-- name: FilterAppsByNameAndByAccountIDOrderedByName :many
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "account_id" = $1 AND "name" ILIKE $2
ORDER BY "name" ASC
OFFSET $3 LIMIT $4
`

type FilterAppsByNameAndByAccountIDOrderedByNameParams struct {
	AccountID int32
	Name      string
	Offset    int32
	Limit     int32
}

func (q *Queries) FilterAppsByNameAndByAccountIDOrderedByName(ctx context.Context, arg FilterAppsByNameAndByAccountIDOrderedByNameParams) ([]App, error) {
	rows, err := q.db.Query(ctx, filterAppsByNameAndByAccountIDOrderedByName,
		arg.AccountID,
		arg.Name,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Name,
			&i.ClientID,
			&i.ClientSecret,
			&i.ConfirmationUri,
			&i.ResetUri,
			&i.CallbackUris,
			&i.LogoutUris,
			&i.DefaultScopes,
			&i.UserRoles,
			&i.AuthProviders,
			&i.UsernameColumn,
			&i.IDTokenTtl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAppByClientID = `-- name: FindAppByClientID :one
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "client_id" = $1 LIMIT 1
`

func (q *Queries) FindAppByClientID(ctx context.Context, clientID string) (App, error) {
	row := q.db.QueryRow(ctx, findAppByClientID, clientID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.ConfirmationUri,
		&i.ResetUri,
		&i.CallbackUris,
		&i.LogoutUris,
		&i.DefaultScopes,
		&i.UserRoles,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.IDTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAppByID = `-- name: FindAppByID :one
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) FindAppByID(ctx context.Context, id int32) (App, error) {
	row := q.db.QueryRow(ctx, findAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.ConfirmationUri,
		&i.ResetUri,
		&i.CallbackUris,
		&i.LogoutUris,
		&i.DefaultScopes,
		&i.UserRoles,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.IDTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPaginatedAppsByAccountIDOrderedByID = `-- name: FindPaginatedAppsByAccountIDOrderedByID :many
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "account_id" = $1
ORDER BY "id" DESC
OFFSET $2 LIMIT $3
`

type FindPaginatedAppsByAccountIDOrderedByIDParams struct {
	AccountID int32
	Offset    int32
	Limit     int32
}

func (q *Queries) FindPaginatedAppsByAccountIDOrderedByID(ctx context.Context, arg FindPaginatedAppsByAccountIDOrderedByIDParams) ([]App, error) {
	rows, err := q.db.Query(ctx, findPaginatedAppsByAccountIDOrderedByID, arg.AccountID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Name,
			&i.ClientID,
			&i.ClientSecret,
			&i.ConfirmationUri,
			&i.ResetUri,
			&i.CallbackUris,
			&i.LogoutUris,
			&i.DefaultScopes,
			&i.UserRoles,
			&i.AuthProviders,
			&i.UsernameColumn,
			&i.IDTokenTtl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaginatedAppsByAccountIDOrderedByName = `-- name: FindPaginatedAppsByAccountIDOrderedByName :many
SELECT id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at FROM "apps"
WHERE "account_id" = $1
ORDER BY "name" ASC
OFFSET $2 LIMIT $3
`

type FindPaginatedAppsByAccountIDOrderedByNameParams struct {
	AccountID int32
	Offset    int32
	Limit     int32
}

func (q *Queries) FindPaginatedAppsByAccountIDOrderedByName(ctx context.Context, arg FindPaginatedAppsByAccountIDOrderedByNameParams) ([]App, error) {
	rows, err := q.db.Query(ctx, findPaginatedAppsByAccountIDOrderedByName, arg.AccountID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Name,
			&i.ClientID,
			&i.ClientSecret,
			&i.ConfirmationUri,
			&i.ResetUri,
			&i.CallbackUris,
			&i.LogoutUris,
			&i.DefaultScopes,
			&i.UserRoles,
			&i.AuthProviders,
			&i.UsernameColumn,
			&i.IDTokenTtl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApp = `-- name: UpdateApp :one
UPDATE "apps"
SET "name" = $2,
    "confirmation_uri" = $3,
    "reset_uri" = $4,
    "callback_uris" = $5,
    "logout_uris" = $6,
    "user_roles" = $7,
    "default_scopes" = $8,
    "auth_providers" = $9,
    "id_token_ttl" = $10,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at
`

type UpdateAppParams struct {
	ID              int32
	Name            string
	ConfirmationUri string
	ResetUri        string
	CallbackUris    []string
	LogoutUris      []string
	UserRoles       []byte
	DefaultScopes   []byte
	AuthProviders   []byte
	IDTokenTtl      int32
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.Name,
		arg.ConfirmationUri,
		arg.ResetUri,
		arg.CallbackUris,
		arg.LogoutUris,
		arg.UserRoles,
		arg.DefaultScopes,
		arg.AuthProviders,
		arg.IDTokenTtl,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.ConfirmationUri,
		&i.ResetUri,
		&i.CallbackUris,
		&i.LogoutUris,
		&i.DefaultScopes,
		&i.UserRoles,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.IDTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppClientSecret = `-- name: UpdateAppClientSecret :one
UPDATE "apps" SET
    "client_secret" = $1,
    "updated_at" = now()
WHERE "id" = $2
RETURNING id, account_id, type, name, client_id, client_secret, confirmation_uri, reset_uri, callback_uris, logout_uris, default_scopes, user_roles, auth_providers, username_column, id_token_ttl, created_at, updated_at
`

type UpdateAppClientSecretParams struct {
	ClientSecret string
	ID           int32
}

func (q *Queries) UpdateAppClientSecret(ctx context.Context, arg UpdateAppClientSecretParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppClientSecret, arg.ClientSecret, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.ConfirmationUri,
		&i.ResetUri,
		&i.CallbackUris,
		&i.LogoutUris,
		&i.DefaultScopes,
		&i.UserRoles,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.IDTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
