// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_providers.sql

package database

import (
	"context"
)

const createAuthProvider = `-- name: CreateAuthProvider :exec

INSERT INTO "auth_providers" (
  "email",
  "provider"
) VALUES (
  $1,
  $2
)
`

type CreateAuthProviderParams struct {
	Email    string
	Provider string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) error {
	_, err := q.db.Exec(ctx, createAuthProvider, arg.Email, arg.Provider)
	return err
}

const deleteExternalAuthProviders = `-- name: DeleteExternalAuthProviders :exec
DELETE FROM "auth_providers"
WHERE 
  "email" = $1 AND 
  "provider" != $2
`

type DeleteExternalAuthProvidersParams struct {
	Email    string
	Provider string
}

func (q *Queries) DeleteExternalAuthProviders(ctx context.Context, arg DeleteExternalAuthProvidersParams) error {
	_, err := q.db.Exec(ctx, deleteExternalAuthProviders, arg.Email, arg.Provider)
	return err
}

const findAuthProviderByEmailAndProvider = `-- name: FindAuthProviderByEmailAndProvider :one
SELECT id, email, provider, created_at, updated_at FROM "auth_providers"
WHERE 
  "email" = $1 AND 
  "provider" = $2
LIMIT 1
`

type FindAuthProviderByEmailAndProviderParams struct {
	Email    string
	Provider string
}

func (q *Queries) FindAuthProviderByEmailAndProvider(ctx context.Context, arg FindAuthProviderByEmailAndProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, findAuthProviderByEmailAndProvider, arg.Email, arg.Provider)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
