// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credentials_keys.sql

package database

import (
	"context"
	"time"
)

const createCredentialsKey = `-- name: CreateCredentialsKey :one

INSERT INTO "credentials_keys" (
    "account_id",
    "public_kid",
    "public_key",
    "expires_at"
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, account_id, public_kid, public_key, jwt_crypto_suite, is_revoked, expires_at, created_at, updated_at
`

type CreateCredentialsKeyParams struct {
	AccountID int32
	PublicKid string
	PublicKey []byte
	ExpiresAt time.Time
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateCredentialsKey(ctx context.Context, arg CreateCredentialsKeyParams) (CredentialsKey, error) {
	row := q.db.QueryRow(ctx, createCredentialsKey,
		arg.AccountID,
		arg.PublicKid,
		arg.PublicKey,
		arg.ExpiresAt,
	)
	var i CredentialsKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublicKid,
		&i.PublicKey,
		&i.JwtCryptoSuite,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeCredentialsKey = `-- name: RevokeCredentialsKey :one
UPDATE "credentials_keys" SET
    "is_revoked" = true,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, account_id, public_kid, public_key, jwt_crypto_suite, is_revoked, expires_at, created_at, updated_at
`

func (q *Queries) RevokeCredentialsKey(ctx context.Context, id int32) (CredentialsKey, error) {
	row := q.db.QueryRow(ctx, revokeCredentialsKey, id)
	var i CredentialsKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublicKid,
		&i.PublicKey,
		&i.JwtCryptoSuite,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
