// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials_secrets.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredentialsSecret = `-- name: CreateCredentialsSecret :one

INSERT INTO "credentials_secrets" (
    "account_id",
    "secret_id",
    "client_secret",
    "storage_mode",
    "dek_kid",
    "expires_at",
    "usage"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING "id"
`

type CreateCredentialsSecretParams struct {
	AccountID    int32
	SecretID     string
	ClientSecret string
	StorageMode  SecretStorageMode
	DekKid       pgtype.Text
	ExpiresAt    time.Time
	Usage        CredentialsUsage
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateCredentialsSecret(ctx context.Context, arg CreateCredentialsSecretParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCredentialsSecret,
		arg.AccountID,
		arg.SecretID,
		arg.ClientSecret,
		arg.StorageMode,
		arg.DekKid,
		arg.ExpiresAt,
		arg.Usage,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteAllCredentialsSecrets = `-- name: DeleteAllCredentialsSecrets :exec
DELETE FROM "credentials_secrets"
`

func (q *Queries) DeleteAllCredentialsSecrets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCredentialsSecrets)
	return err
}

const findValidCredentialsSecretBySecretID = `-- name: FindValidCredentialsSecretBySecretID :one
SELECT id, secret_id, client_secret, storage_mode, dek_kid, is_revoked, usage, account_id, expires_at, created_at, updated_at FROM "credentials_secrets"
WHERE
    "secret_id" = $1 AND
    "is_revoked" = false AND
    "expires_at" > now()
LIMIT 1
`

func (q *Queries) FindValidCredentialsSecretBySecretID(ctx context.Context, secretID string) (CredentialsSecret, error) {
	row := q.db.QueryRow(ctx, findValidCredentialsSecretBySecretID, secretID)
	var i CredentialsSecret
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.ClientSecret,
		&i.StorageMode,
		&i.DekKid,
		&i.IsRevoked,
		&i.Usage,
		&i.AccountID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeCredentialsSecret = `-- name: RevokeCredentialsSecret :one
UPDATE "credentials_secrets" SET
    "is_revoked" = true,
    "updated_at" = now()
WHERE "id" = $1
RETURNING id, secret_id, client_secret, storage_mode, dek_kid, is_revoked, usage, account_id, expires_at, created_at, updated_at
`

func (q *Queries) RevokeCredentialsSecret(ctx context.Context, id int32) (CredentialsSecret, error) {
	row := q.db.QueryRow(ctx, revokeCredentialsSecret, id)
	var i CredentialsSecret
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.ClientSecret,
		&i.StorageMode,
		&i.DekKid,
		&i.IsRevoked,
		&i.Usage,
		&i.AccountID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentialsSecretClientSecret = `-- name: UpdateCredentialsSecretClientSecret :exec
UPDATE "credentials_secrets" SET
    "client_secret" = $2,
    "dek_kid" = $3,
    "updated_at" = now()
WHERE "id" = $1
`

type UpdateCredentialsSecretClientSecretParams struct {
	ID           int32
	ClientSecret string
	DekKid       pgtype.Text
}

func (q *Queries) UpdateCredentialsSecretClientSecret(ctx context.Context, arg UpdateCredentialsSecretClientSecretParams) error {
	_, err := q.db.Exec(ctx, updateCredentialsSecretClientSecret, arg.ID, arg.ClientSecret, arg.DekKid)
	return err
}

const updateCredentialsSecretExpiresAtAndCreatedAt = `-- name: UpdateCredentialsSecretExpiresAtAndCreatedAt :exec
UPDATE "credentials_secrets" SET
    "expires_at" = $2,
    "created_at" = $3,
    "updated_at" = now()
WHERE "secret_id" = $1
`

type UpdateCredentialsSecretExpiresAtAndCreatedAtParams struct {
	SecretID  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) UpdateCredentialsSecretExpiresAtAndCreatedAt(ctx context.Context, arg UpdateCredentialsSecretExpiresAtAndCreatedAtParams) error {
	_, err := q.db.Exec(ctx, updateCredentialsSecretExpiresAtAndCreatedAt, arg.SecretID, arg.ExpiresAt, arg.CreatedAt)
	return err
}
