// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dynamic_registration_domains.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countDynamicRegistrationDomainsByAccountPublicID = `-- name: CountDynamicRegistrationDomainsByAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE "account_public_id" = $1
`

func (q *Queries) CountDynamicRegistrationDomainsByAccountPublicID(ctx context.Context, accountPublicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRegistrationDomainsByAccountPublicID, accountPublicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDynamicRegistrationDomainsByDomain = `-- name: CountDynamicRegistrationDomainsByDomain :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE "domain" = $1
LIMIT 1
`

func (q *Queries) CountDynamicRegistrationDomainsByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRegistrationDomainsByDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDynamicRegistrationDomainsByDomainAndAccountPublicID = `-- name: CountDynamicRegistrationDomainsByDomainAndAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" = $2
LIMIT 1
`

type CountDynamicRegistrationDomainsByDomainAndAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Domain          string
}

func (q *Queries) CountDynamicRegistrationDomainsByDomainAndAccountPublicID(ctx context.Context, arg CountDynamicRegistrationDomainsByDomainAndAccountPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRegistrationDomainsByDomainAndAccountPublicID, arg.AccountPublicID, arg.Domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDynamicRegistrationDomainsByDomains = `-- name: CountDynamicRegistrationDomainsByDomains :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE "domain" IN ($1)
LIMIT 1
`

func (q *Queries) CountDynamicRegistrationDomainsByDomains(ctx context.Context, domains []string) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRegistrationDomainsByDomains, domains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDynamicRegistrationDomainsByDomainsAndAccountPublicID = `-- name: CountDynamicRegistrationDomainsByDomainsAndAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" IN ($2)
LIMIT 1
`

type CountDynamicRegistrationDomainsByDomainsAndAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Domains         []string
}

func (q *Queries) CountDynamicRegistrationDomainsByDomainsAndAccountPublicID(ctx context.Context, arg CountDynamicRegistrationDomainsByDomainsAndAccountPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDynamicRegistrationDomainsByDomainsAndAccountPublicID, arg.AccountPublicID, arg.Domains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilteredDynamicRegistrationDomainsByAccountPublicID = `-- name: CountFilteredDynamicRegistrationDomainsByAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" ILIKE $2
LIMIT 1
`

type CountFilteredDynamicRegistrationDomainsByAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Domain          string
}

func (q *Queries) CountFilteredDynamicRegistrationDomainsByAccountPublicID(ctx context.Context, arg CountFilteredDynamicRegistrationDomainsByAccountPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredDynamicRegistrationDomainsByAccountPublicID, arg.AccountPublicID, arg.Domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerifiedDynamicRegistrationDomainsByDomain = `-- name: CountVerifiedDynamicRegistrationDomainsByDomain :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE "domain" = $1 AND "verified_at" IS NOT NULL
LIMIT 1
`

func (q *Queries) CountVerifiedDynamicRegistrationDomainsByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedDynamicRegistrationDomainsByDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicID = `-- name: CountVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" = $2 AND
    "verified_at" IS NOT NULL
LIMIT 1
`

type CountVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Domain          string
}

func (q *Queries) CountVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicID(ctx context.Context, arg CountVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedDynamicRegistrationDomainsByDomainAndAccountPublicID, arg.AccountPublicID, arg.Domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerifiedDynamicRegistrationDomainsByDomains = `-- name: CountVerifiedDynamicRegistrationDomainsByDomains :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE "domain" IN ($1) AND "verified_at" IS NOT NULL
LIMIT 1
`

func (q *Queries) CountVerifiedDynamicRegistrationDomainsByDomains(ctx context.Context, domains []string) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedDynamicRegistrationDomainsByDomains, domains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicID = `-- name: CountVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicID :one
SELECT COUNT(*) FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" IN ($2) AND
    "verified_at" IS NOT NULL
LIMIT 1
`

type CountVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicIDParams struct {
	AccountPublicID uuid.UUID
	Domains         []string
}

func (q *Queries) CountVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicID(ctx context.Context, arg CountVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedDynamicRegistrationDomainsByDomainsAndAccountPublicID, arg.AccountPublicID, arg.Domains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDynamicRegistrationDomain = `-- name: CreateDynamicRegistrationDomain :one

INSERT INTO "dynamic_registration_domains" (
    "account_id",
    "account_public_id",
    "domain",
    "verification_method",
    "usages"
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at
`

type CreateDynamicRegistrationDomainParams struct {
	AccountID          int32
	AccountPublicID    uuid.UUID
	Domain             string
	VerificationMethod DomainVerificationMethod
	Usages             []DynamicRegistrationUsage
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateDynamicRegistrationDomain(ctx context.Context, arg CreateDynamicRegistrationDomainParams) (DynamicRegistrationDomain, error) {
	row := q.db.QueryRow(ctx, createDynamicRegistrationDomain,
		arg.AccountID,
		arg.AccountPublicID,
		arg.Domain,
		arg.VerificationMethod,
		arg.Usages,
	)
	var i DynamicRegistrationDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.Usages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDynamicRegistrationDomain = `-- name: DeleteDynamicRegistrationDomain :exec
DELETE FROM "dynamic_registration_domains"
WHERE "id" = $1
`

func (q *Queries) DeleteDynamicRegistrationDomain(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDynamicRegistrationDomain, id)
	return err
}

const filterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain = `-- name: FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain :many
SELECT id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" ILIKE $2
ORDER BY "domain" ASC
LIMIT $3 OFFSET $4
`

type FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomainParams struct {
	AccountPublicID uuid.UUID
	Domain          string
	Limit           int32
	Offset          int32
}

func (q *Queries) FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain(ctx context.Context, arg FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomainParams) ([]DynamicRegistrationDomain, error) {
	rows, err := q.db.Query(ctx, filterDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain,
		arg.AccountPublicID,
		arg.Domain,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DynamicRegistrationDomain{}
	for rows.Next() {
		var i DynamicRegistrationDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.Domain,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.Usages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterDynamicRegistrationDomainsByAccountPublicIDOrderedByID = `-- name: FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByID :many
SELECT id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at FROM "dynamic_registration_domains"
WHERE
    "account_public_id" = $1 AND
    "domain" ILIKE $2
ORDER BY "id" DESC
LIMIT $3 OFFSET $4
`

type FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByIDParams struct {
	AccountPublicID uuid.UUID
	Domain          string
	Limit           int32
	Offset          int32
}

func (q *Queries) FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByID(ctx context.Context, arg FilterDynamicRegistrationDomainsByAccountPublicIDOrderedByIDParams) ([]DynamicRegistrationDomain, error) {
	rows, err := q.db.Query(ctx, filterDynamicRegistrationDomainsByAccountPublicIDOrderedByID,
		arg.AccountPublicID,
		arg.Domain,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DynamicRegistrationDomain{}
	for rows.Next() {
		var i DynamicRegistrationDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.Domain,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.Usages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDynamicRegistrationDomainByAccountPublicIDAndDomain = `-- name: FindDynamicRegistrationDomainByAccountPublicIDAndDomain :one
SELECT id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at FROM "dynamic_registration_domains" WHERE "account_public_id" = $1 AND "domain" = $2 LIMIT 1
`

type FindDynamicRegistrationDomainByAccountPublicIDAndDomainParams struct {
	AccountPublicID uuid.UUID
	Domain          string
}

func (q *Queries) FindDynamicRegistrationDomainByAccountPublicIDAndDomain(ctx context.Context, arg FindDynamicRegistrationDomainByAccountPublicIDAndDomainParams) (DynamicRegistrationDomain, error) {
	row := q.db.QueryRow(ctx, findDynamicRegistrationDomainByAccountPublicIDAndDomain, arg.AccountPublicID, arg.Domain)
	var i DynamicRegistrationDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.Usages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain = `-- name: FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain :many
SELECT id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at FROM "dynamic_registration_domains"
WHERE "account_public_id" = $1
ORDER BY "domain" ASC
LIMIT $2 OFFSET $3
`

type FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomainParams struct {
	AccountPublicID uuid.UUID
	Limit           int32
	Offset          int32
}

func (q *Queries) FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain(ctx context.Context, arg FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomainParams) ([]DynamicRegistrationDomain, error) {
	rows, err := q.db.Query(ctx, findPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByDomain, arg.AccountPublicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DynamicRegistrationDomain{}
	for rows.Next() {
		var i DynamicRegistrationDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.Domain,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.Usages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByID = `-- name: FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByID :many
SELECT id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at FROM "dynamic_registration_domains"
WHERE "account_public_id" = $1
ORDER BY "id" DESC
LIMIT $2 OFFSET $3
`

type FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByIDParams struct {
	AccountPublicID uuid.UUID
	Limit           int32
	Offset          int32
}

func (q *Queries) FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByID(ctx context.Context, arg FindPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByIDParams) ([]DynamicRegistrationDomain, error) {
	rows, err := q.db.Query(ctx, findPaginatedDynamicRegistrationDomainsByAccountPublicIDOrderedByID, arg.AccountPublicID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DynamicRegistrationDomain{}
	for rows.Next() {
		var i DynamicRegistrationDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountPublicID,
			&i.Domain,
			&i.VerifiedAt,
			&i.VerificationMethod,
			&i.Usages,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyDynamicRegistrationDomain = `-- name: VerifyDynamicRegistrationDomain :one
UPDATE "dynamic_registration_domains"
SET
    "verified_at" = NOW(),
    "verification_method" = $2
WHERE "id" = $1 RETURNING id, account_id, account_public_id, domain, verified_at, verification_method, usages, created_at, updated_at
`

type VerifyDynamicRegistrationDomainParams struct {
	ID                 int32
	VerificationMethod DomainVerificationMethod
}

func (q *Queries) VerifyDynamicRegistrationDomain(ctx context.Context, arg VerifyDynamicRegistrationDomainParams) (DynamicRegistrationDomain, error) {
	row := q.db.QueryRow(ctx, verifyDynamicRegistrationDomain, arg.ID, arg.VerificationMethod)
	var i DynamicRegistrationDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.Domain,
		&i.VerifiedAt,
		&i.VerificationMethod,
		&i.Usages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
