// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dynamic_registration_software_statement_keys.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const findDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicID = `-- name: FindDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicID :one
SELECT id, account_id, account_public_id, credentials_key_id, credentials_key_kid, root_domain, created_at FROM "dynamic_registration_software_statement_keys"
WHERE "credentials_key_kid" = $1 AND "account_public_id" = $2
LIMIT 1
`

type FindDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicIDParams struct {
	CredentialsKeyKid string
	AccountPublicID   uuid.UUID
}

func (q *Queries) FindDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicID(ctx context.Context, arg FindDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicIDParams) (DynamicRegistrationSoftwareStatementKey, error) {
	row := q.db.QueryRow(ctx, findDynamicRegistrationSoftwareStatementKeysByCredentialsKeyKIDAndAccountPublicID, arg.CredentialsKeyKid, arg.AccountPublicID)
	var i DynamicRegistrationSoftwareStatementKey
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.CredentialsKeyID,
		&i.CredentialsKeyKid,
		&i.RootDomain,
		&i.CreatedAt,
	)
	return i, err
}

const findDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicID = `-- name: FindDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicID :one

SELECT c.id, c.public_kid, c.public_key, c.crypto_suite, c.is_revoked, c.is_external, c.usage, c.account_id, c.expires_at, c.created_at, c.updated_at FROM "credentials_keys" AS "c"
LEFT JOIN "dynamic_registration_software_statement_keys" AS "d" ON "c"."id" = "d"."credential_key_id"
WHERE "d"."root_domain" = $1 AND "d"."account_public_id" = $2
LIMIT 1
`

type FindDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicIDParams struct {
	RootDomain      string
	AccountPublicID uuid.UUID
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) FindDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicID(ctx context.Context, arg FindDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicIDParams) (CredentialsKey, error) {
	row := q.db.QueryRow(ctx, findDynamicRegistrationSoftwareStatementKeysByRootDomainAndAccountPublicID, arg.RootDomain, arg.AccountPublicID)
	var i CredentialsKey
	err := row.Scan(
		&i.ID,
		&i.PublicKid,
		&i.PublicKey,
		&i.CryptoSuite,
		&i.IsRevoked,
		&i.IsExternal,
		&i.Usage,
		&i.AccountID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
