// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGrant = `-- name: CreateGrant :one

INSERT INTO "grants" (
  "account_id",
  "grant_id",
  "granted_client_id",
  "granted_scopes",
  "granted_custom_scopes"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
) RETURNING id
`

type CreateGrantParams struct {
	AccountID           int32
	GrantID             uuid.UUID
	GrantedClientID     string
	GrantedScopes       []Scopes
	GrantedCustomScopes []string
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (int32, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.AccountID,
		arg.GrantID,
		arg.GrantedClientID,
		arg.GrantedScopes,
		arg.GrantedCustomScopes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
