// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int32
	GivenName     string
	FamilyName    string
	Username      string
	Email         string
	Organization  pgtype.Text
	Dek           string
	Password      pgtype.Text
	Version       int32
	EmailVerified bool
	IsActive      bool
	TwoFactorType string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AccountCredential struct {
	ID           int32
	AccountID    int32
	Scopes       []byte
	Alias        string
	ClientID     string
	ClientSecret string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AccountKey struct {
	ID             int32
	AccountID      int32
	OidcConfigID   int32
	Name           string
	JwtCryptoSuite string
	PublicKid      string
	PublicKey      []byte
	PrivateKey     string
	IsDistributed  bool
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AccountTotp struct {
	ID            int32
	AccountID     int32
	Url           string
	Secret        string
	RecoveryCodes []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type App struct {
	ID              int32
	AccountID       int32
	Type            string
	Name            string
	ClientID        string
	ClientSecret    string
	ConfirmationUri string
	CallbackUris    []string
	LogoutUris      []string
	DefaultScopes   []byte
	UserRoles       []byte
	AuthProviders   []byte
	UsernameColumn  string
	IDTokenTtl      int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AppProfile struct {
	ID        int32
	AccountID int32
	UserID    int32
	AppID     int32
	UserRoles []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuthProvider struct {
	ID        int32
	Email     string
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BlacklistedToken struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type ExternalAuthProvider struct {
	ID           int32
	Name         string
	Provider     string
	Icon         string
	AccountID    int32
	ClientID     string
	ClientSecret string
	Scopes       []string
	AuthUrl      string
	TokenUrl     string
	UserInfoUrl  string
	EmailKey     string
	UserSchema   []byte
	UserMapping  []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type OidcConfig struct {
	ID             int32
	AccountID      int32
	Dek            string
	Claims         []byte
	Scopes         []byte
	JwtCryptoSuite string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID            int32
	AccountID     int32
	Email         string
	Username      string
	Password      pgtype.Text
	Dek           string
	Version       int32
	EmailVerified bool
	IsActive      bool
	TwoFactorType string
	UserData      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserAuthProvider struct {
	ID        int32
	UserID    int32
	AccountID int32
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserCredential struct {
	ID           int32
	UserID       int32
	ClientID     string
	ClientSecret string
	AccountID    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserTotp struct {
	ID            int32
	AccountID     int32
	UserID        int32
	Url           string
	Secret        string
	RecoveryCodes []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
