// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            int32
	FirstName     string
	LastName      string
	Username      string
	Email         string
	Dek           string
	Password      pgtype.Text
	Version       int32
	IsConfirmed   bool
	TwoFactorType string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AccountCredential struct {
	ID           int32
	AccountID    int32
	Scopes       []byte
	Alias        string
	ClientID     string
	ClientSecret string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AccountTotp struct {
	ID            int32
	AccountID     int32
	Url           string
	Secret        string
	RecoveryCodes []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type App struct {
	ID              int32
	AccountID       int32
	Type            string
	Name            string
	ClientID        string
	ClientSecret    string
	Dek             string
	ConfirmationUri string
	CallbackUris    []string
	LogoutUris      []string
	UserScopes      []byte
	UserRoles       []byte
	AuthProviders   []byte
	UsernameColumn  string
	ProfileSchema   []byte
	IDTokenTtl      int32
	JwtCryptoSuite  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AppKey struct {
	ID             int32
	AppID          int32
	AccountID      int32
	Name           string
	JwtCryptoSuite string
	PublicKid      string
	PublicKey      []byte
	PrivateKey     string
	IsDistributed  bool
	ExpiresAt      time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AppProfile struct {
	ID          int32
	AccountID   int32
	UserID      int32
	AppID       int32
	UserRoles   []byte
	ProfileData []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AuthProvider struct {
	ID        int32
	Email     string
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BlacklistedToken struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type ExternalAuthProvider struct {
	ID           int32
	Name         string
	Provider     string
	Icon         string
	AccountID    int32
	ClientID     string
	ClientSecret string
	Scopes       []string
	AuthUrl      string
	TokenUrl     string
	UserInfoUrl  string
	UserSchema   []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User struct {
	ID            int32
	AccountID     int32
	Email         string
	Username      string
	Password      pgtype.Text
	Dek           string
	Version       int32
	IsConfirmed   bool
	TwoFactorType string
	UserData      []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserAuthProvider struct {
	ID        int32
	UserID    int32
	AccountID int32
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserCredential struct {
	ID           int32
	UserID       int32
	ClientID     string
	ClientSecret string
	AccountID    int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserSchema struct {
	ID         int32
	AccountID  int32
	SchemaData []byte
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UserTotp struct {
	ID            int32
	AccountID     int32
	UserID        int32
	Url           string
	Secret        string
	RecoveryCodes []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
