// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registered_apps.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRegisteredApp = `-- name: CreateRegisteredApp :one
INSERT INTO "apps" (
  "account_id",
  "account_public_id",
  "app_type",
  "client_name",
  "client_id",
  "client_uri",
  "username_column",
  "token_endpoint_auth_method",
  "creation_method",
  "grant_types",
  "logo_uri",
  "tos_uri",
  "policy_uri",
  "contacts",
  "software_id",
  "software_version",
  "scopes",
  "default_scopes",
  "custom_scopes",
  "default_custom_scopes",
  "domain",
  "transport",
  "redirect_uris",
  "response_types",
  "allow_user_registration",
  "auth_providers",
  "jwks_uri",
  "jwks",
  "sector_identifier_uri",
  "subject_type",
  "id_token_signed_response_alg",
  "id_token_encrypted_response_alg",
  "id_token_encrypted_response_enc",
  "userinfo_signed_response_alg",
  "userinfo_encrypted_response_alg",
  "userinfo_encrypted_response_enc",
  "request_object_signing_alg",
  "request_object_encryption_alg",
  "request_object_encryption_enc",
  "token_endpoint_auth_signing_alg",
  "default_max_age",
  "require_auth_time",
  "default_acr_values",
  "initiate_login_uri",
  "request_uris",
  "access_token_signing_alg"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27,
  $28,
  $29,
  $30,
  $31,
  $32,
  $33,
  $34,
  $35,
  $36,
  $37,
  $38,
  $39,
  $40,
  $41,
  $42,
  $43,
  $44,
  $45,
  $46
) RETURNING id, account_id, account_public_id, client_id, version, creation_method, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, custom_scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, domain, transport, allow_user_registration, auth_providers, username_column, default_scopes, default_custom_scopes, app_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, id_token_ttl, token_ttl, refresh_token_ttl, created_at, updated_at
`

type CreateRegisteredAppParams struct {
	AccountID                    int32
	AccountPublicID              uuid.UUID
	AppType                      AppType
	ClientName                   string
	ClientID                     string
	ClientUri                    string
	UsernameColumn               AppUsernameColumn
	TokenEndpointAuthMethod      AuthMethod
	CreationMethod               CreationMethod
	GrantTypes                   []GrantType
	LogoUri                      pgtype.Text
	TosUri                       pgtype.Text
	PolicyUri                    pgtype.Text
	Contacts                     []string
	SoftwareID                   pgtype.Text
	SoftwareVersion              pgtype.Text
	Scopes                       []Scopes
	DefaultScopes                []Scopes
	CustomScopes                 []string
	DefaultCustomScopes          []string
	Domain                       string
	Transport                    Transport
	RedirectUris                 []string
	ResponseTypes                []ResponseType
	AllowUserRegistration        bool
	AuthProviders                []AuthProvider
	JwksUri                      pgtype.Text
	Jwks                         []byte
	SectorIdentifierUri          pgtype.Text
	SubjectType                  NullClientSubjectType
	IDTokenSignedResponseAlg     TokenCryptoSuite
	IDTokenEncryptedResponseAlg  NullTokenEncryptionAlgorithm
	IDTokenEncryptedResponseEnc  NullTokenEncryptionEncoding
	UserinfoSignedResponseAlg    NullTokenCryptoSuite
	UserinfoEncryptedResponseAlg NullTokenEncryptionAlgorithm
	UserinfoEncryptedResponseEnc NullTokenEncryptionEncoding
	RequestObjectSigningAlg      NullTokenCryptoSuite
	RequestObjectEncryptionAlg   NullTokenEncryptionAlgorithm
	RequestObjectEncryptionEnc   NullTokenEncryptionEncoding
	TokenEndpointAuthSigningAlg  NullTokenCryptoSuite
	DefaultMaxAge                pgtype.Int4
	RequireAuthTime              bool
	DefaultAcrValues             []string
	InitiateLoginUri             pgtype.Text
	RequestUris                  []string
	AccessTokenSigningAlg        TokenCryptoSuite
}

func (q *Queries) CreateRegisteredApp(ctx context.Context, arg CreateRegisteredAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createRegisteredApp,
		arg.AccountID,
		arg.AccountPublicID,
		arg.AppType,
		arg.ClientName,
		arg.ClientID,
		arg.ClientUri,
		arg.UsernameColumn,
		arg.TokenEndpointAuthMethod,
		arg.CreationMethod,
		arg.GrantTypes,
		arg.LogoUri,
		arg.TosUri,
		arg.PolicyUri,
		arg.Contacts,
		arg.SoftwareID,
		arg.SoftwareVersion,
		arg.Scopes,
		arg.DefaultScopes,
		arg.CustomScopes,
		arg.DefaultCustomScopes,
		arg.Domain,
		arg.Transport,
		arg.RedirectUris,
		arg.ResponseTypes,
		arg.AllowUserRegistration,
		arg.AuthProviders,
		arg.JwksUri,
		arg.Jwks,
		arg.SectorIdentifierUri,
		arg.SubjectType,
		arg.IDTokenSignedResponseAlg,
		arg.IDTokenEncryptedResponseAlg,
		arg.IDTokenEncryptedResponseEnc,
		arg.UserinfoSignedResponseAlg,
		arg.UserinfoEncryptedResponseAlg,
		arg.UserinfoEncryptedResponseEnc,
		arg.RequestObjectSigningAlg,
		arg.RequestObjectEncryptionAlg,
		arg.RequestObjectEncryptionEnc,
		arg.TokenEndpointAuthSigningAlg,
		arg.DefaultMaxAge,
		arg.RequireAuthTime,
		arg.DefaultAcrValues,
		arg.InitiateLoginUri,
		arg.RequestUris,
		arg.AccessTokenSigningAlg,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.ClientID,
		&i.Version,
		&i.CreationMethod,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.CustomScopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.Domain,
		&i.Transport,
		&i.AllowUserRegistration,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.DefaultScopes,
		&i.DefaultCustomScopes,
		&i.AppType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.IDTokenTtl,
		&i.TokenTtl,
		&i.RefreshTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegisteredApp = `-- name: UpdateRegisteredApp :one
UPDATE "apps" SET
  "client_name" = $2,
  "client_uri" = $3,
  "username_column" = $4,
  "token_endpoint_auth_method" = $5,
  "grant_types" = $6,
  "logo_uri" = $7,
  "tos_uri" = $8,
  "policy_uri" = $9,
  "contacts" = $10,
  "software_id" = $11,
  "software_version" = $12,
  "scopes" = $13,
  "default_scopes" = $14,
  "custom_scopes" = $15,
  "default_custom_scopes" = $16,
  "domain" = $17,
  "transport" = $18,
  "redirect_uris" = $19,
  "response_types" = $20,
  "allow_user_registration" = $21,
  "auth_providers" = $22,
  "jwks_uri" = $23,
  "jwks" = $24,
  "sector_identifier_uri" = $25,
  "subject_type" = $26,
  "id_token_signed_response_alg" = $27,
  "id_token_encrypted_response_alg" = $28,
  "id_token_encrypted_response_enc" = $29,
  "userinfo_signed_response_alg" = $30,
  "userinfo_encrypted_response_alg" = $31,
  "userinfo_encrypted_response_enc" = $32,
  "request_object_signing_alg" = $33,
  "request_object_encryption_alg" = $34,
  "request_object_encryption_enc" = $35,
  "token_endpoint_auth_signing_alg" = $36,
  "default_max_age" = $37,
  "require_auth_time" = $38,
  "default_acr_values" = $39,
  "initiate_login_uri" = $40,
  "request_uris" = $41,
  "access_token_signing_alg" = $42,
  "version" = "version" + 1,
  "updated_at" = now()
WHERE "id" = $1
RETURNING id, account_id, account_public_id, client_id, version, creation_method, redirect_uris, token_endpoint_auth_method, grant_types, response_types, client_name, client_uri, logo_uri, scopes, custom_scopes, contacts, tos_uri, policy_uri, jwks_uri, jwks, software_id, software_version, domain, transport, allow_user_registration, auth_providers, username_column, default_scopes, default_custom_scopes, app_type, sector_identifier_uri, subject_type, id_token_signed_response_alg, id_token_encrypted_response_alg, id_token_encrypted_response_enc, userinfo_signed_response_alg, userinfo_encrypted_response_alg, userinfo_encrypted_response_enc, request_object_signing_alg, request_object_encryption_alg, request_object_encryption_enc, token_endpoint_auth_signing_alg, default_max_age, require_auth_time, default_acr_values, initiate_login_uri, request_uris, access_token_signing_alg, id_token_ttl, token_ttl, refresh_token_ttl, created_at, updated_at
`

type UpdateRegisteredAppParams struct {
	ID                           int32
	ClientName                   string
	ClientUri                    string
	UsernameColumn               AppUsernameColumn
	TokenEndpointAuthMethod      AuthMethod
	GrantTypes                   []GrantType
	LogoUri                      pgtype.Text
	TosUri                       pgtype.Text
	PolicyUri                    pgtype.Text
	Contacts                     []string
	SoftwareID                   pgtype.Text
	SoftwareVersion              pgtype.Text
	Scopes                       []Scopes
	DefaultScopes                []Scopes
	CustomScopes                 []string
	DefaultCustomScopes          []string
	Domain                       string
	Transport                    Transport
	RedirectUris                 []string
	ResponseTypes                []ResponseType
	AllowUserRegistration        bool
	AuthProviders                []AuthProvider
	JwksUri                      pgtype.Text
	Jwks                         []byte
	SectorIdentifierUri          pgtype.Text
	SubjectType                  NullClientSubjectType
	IDTokenSignedResponseAlg     TokenCryptoSuite
	IDTokenEncryptedResponseAlg  NullTokenEncryptionAlgorithm
	IDTokenEncryptedResponseEnc  NullTokenEncryptionEncoding
	UserinfoSignedResponseAlg    NullTokenCryptoSuite
	UserinfoEncryptedResponseAlg NullTokenEncryptionAlgorithm
	UserinfoEncryptedResponseEnc NullTokenEncryptionEncoding
	RequestObjectSigningAlg      NullTokenCryptoSuite
	RequestObjectEncryptionAlg   NullTokenEncryptionAlgorithm
	RequestObjectEncryptionEnc   NullTokenEncryptionEncoding
	TokenEndpointAuthSigningAlg  NullTokenCryptoSuite
	DefaultMaxAge                pgtype.Int4
	RequireAuthTime              bool
	DefaultAcrValues             []string
	InitiateLoginUri             pgtype.Text
	RequestUris                  []string
	AccessTokenSigningAlg        TokenCryptoSuite
}

func (q *Queries) UpdateRegisteredApp(ctx context.Context, arg UpdateRegisteredAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateRegisteredApp,
		arg.ID,
		arg.ClientName,
		arg.ClientUri,
		arg.UsernameColumn,
		arg.TokenEndpointAuthMethod,
		arg.GrantTypes,
		arg.LogoUri,
		arg.TosUri,
		arg.PolicyUri,
		arg.Contacts,
		arg.SoftwareID,
		arg.SoftwareVersion,
		arg.Scopes,
		arg.DefaultScopes,
		arg.CustomScopes,
		arg.DefaultCustomScopes,
		arg.Domain,
		arg.Transport,
		arg.RedirectUris,
		arg.ResponseTypes,
		arg.AllowUserRegistration,
		arg.AuthProviders,
		arg.JwksUri,
		arg.Jwks,
		arg.SectorIdentifierUri,
		arg.SubjectType,
		arg.IDTokenSignedResponseAlg,
		arg.IDTokenEncryptedResponseAlg,
		arg.IDTokenEncryptedResponseEnc,
		arg.UserinfoSignedResponseAlg,
		arg.UserinfoEncryptedResponseAlg,
		arg.UserinfoEncryptedResponseEnc,
		arg.RequestObjectSigningAlg,
		arg.RequestObjectEncryptionAlg,
		arg.RequestObjectEncryptionEnc,
		arg.TokenEndpointAuthSigningAlg,
		arg.DefaultMaxAge,
		arg.RequireAuthTime,
		arg.DefaultAcrValues,
		arg.InitiateLoginUri,
		arg.RequestUris,
		arg.AccessTokenSigningAlg,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountPublicID,
		&i.ClientID,
		&i.Version,
		&i.CreationMethod,
		&i.RedirectUris,
		&i.TokenEndpointAuthMethod,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ClientName,
		&i.ClientUri,
		&i.LogoUri,
		&i.Scopes,
		&i.CustomScopes,
		&i.Contacts,
		&i.TosUri,
		&i.PolicyUri,
		&i.JwksUri,
		&i.Jwks,
		&i.SoftwareID,
		&i.SoftwareVersion,
		&i.Domain,
		&i.Transport,
		&i.AllowUserRegistration,
		&i.AuthProviders,
		&i.UsernameColumn,
		&i.DefaultScopes,
		&i.DefaultCustomScopes,
		&i.AppType,
		&i.SectorIdentifierUri,
		&i.SubjectType,
		&i.IDTokenSignedResponseAlg,
		&i.IDTokenEncryptedResponseAlg,
		&i.IDTokenEncryptedResponseEnc,
		&i.UserinfoSignedResponseAlg,
		&i.UserinfoEncryptedResponseAlg,
		&i.UserinfoEncryptedResponseEnc,
		&i.RequestObjectSigningAlg,
		&i.RequestObjectEncryptionAlg,
		&i.RequestObjectEncryptionEnc,
		&i.TokenEndpointAuthSigningAlg,
		&i.DefaultMaxAge,
		&i.RequireAuthTime,
		&i.DefaultAcrValues,
		&i.InitiateLoginUri,
		&i.RequestUris,
		&i.AccessTokenSigningAlg,
		&i.IDTokenTtl,
		&i.TokenTtl,
		&i.RefreshTokenTtl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
