// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO "sessions" (
  "account_id",
  "grant_id",
  "session_id",
  "session_type",
  "session_client_id",
  "ip_address",
  "user_agent",
  "expires_at"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
) RETURNING "id"
`

type CreateSessionParams struct {
	AccountID       int32
	GrantID         int32
	SessionID       uuid.UUID
	SessionType     SessionType
	SessionClientID string
	IpAddress       pgtype.Text
	UserAgent       pgtype.Text
	ExpiresAt       time.Time
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.GrantID,
		arg.SessionID,
		arg.SessionType,
		arg.SessionClientID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM "sessions" WHERE "id" = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, id)
	return err
}

const updateSessionExpiresAt = `-- name: UpdateSessionExpiresAt :exec
UPDATE "sessions" SET "expires_at" = $1 WHERE "id" = $2
`

type UpdateSessionExpiresAtParams struct {
	ExpiresAt time.Time
	ID        int32
}

func (q *Queries) UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) error {
	_, err := q.db.Exec(ctx, updateSessionExpiresAt, arg.ExpiresAt, arg.ID)
	return err
}
