// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSessionToken = `-- name: CreateSessionToken :exec

INSERT INTO "session_tokens" (
  "token_id",
  "account_id",
  "session_id",
  "session_uuid",
  "grant_id",
  "expires_at"
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type CreateSessionTokenParams struct {
	TokenID     uuid.UUID
	AccountID   int32
	SessionID   int32
	SessionUuid uuid.UUID
	GrantID     int32
	ExpiresAt   time.Time
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateSessionToken(ctx context.Context, arg CreateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, createSessionToken,
		arg.TokenID,
		arg.AccountID,
		arg.SessionID,
		arg.SessionUuid,
		arg.GrantID,
		arg.ExpiresAt,
	)
	return err
}

const deleteSessionToken = `-- name: DeleteSessionToken :exec
DELETE FROM "session_tokens"
WHERE "token_id" = $1
`

func (q *Queries) DeleteSessionToken(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionToken, tokenID)
	return err
}

const findSessionTokenByTokenID = `-- name: FindSessionTokenByTokenID :one
SELECT id, account_id, session_id, grant_id, session_uuid, token_id, issued_at, expires_at, created_at FROM "session_tokens"
WHERE "token_id" = $1 LIMIT 1
`

func (q *Queries) FindSessionTokenByTokenID(ctx context.Context, tokenID uuid.UUID) (SessionToken, error) {
	row := q.db.QueryRow(ctx, findSessionTokenByTokenID, tokenID)
	var i SessionToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SessionID,
		&i.GrantID,
		&i.SessionUuid,
		&i.TokenID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
