// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findUserSessionByUserIDAndSessionUUID = `-- name: FindUserSessionByUserIDAndSessionUUID :one

SELECT u.user_id, u.user_version, u.session_id, u.app_id, u.account_id, u.session_uuid, u.created_at, s.id, s.account_id, s.grant_id, s.session_id, s.session_type, s.session_client_id, s.ip_address, s.user_agent, s.issued_at, s.expires_at, s.created_at, s.updated_at
FROM "user_sessions" AS "u"
LEFT JOIN "sessions" AS "s" ON "u"."session_id" = "s"."id"
WHERE "u"."user_id" = $1
AND "u"."session_uuid" = $2
LIMIT 1
`

type FindUserSessionByUserIDAndSessionUUIDParams struct {
	UserID      int32
	SessionUuid uuid.UUID
}

type FindUserSessionByUserIDAndSessionUUIDRow struct {
	UserID          int32
	UserVersion     int32
	SessionID       int32
	AppID           int32
	AccountID       int32
	SessionUuid     uuid.UUID
	CreatedAt       time.Time
	ID              pgtype.Int4
	AccountID_2     pgtype.Int4
	GrantID         pgtype.Int4
	SessionID_2     pgtype.UUID
	SessionType     NullSessionType
	SessionClientID pgtype.Text
	IpAddress       pgtype.Text
	UserAgent       pgtype.Text
	IssuedAt        pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	CreatedAt_2     pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Copyright (c) 2026 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) FindUserSessionByUserIDAndSessionUUID(ctx context.Context, arg FindUserSessionByUserIDAndSessionUUIDParams) (FindUserSessionByUserIDAndSessionUUIDRow, error) {
	row := q.db.QueryRow(ctx, findUserSessionByUserIDAndSessionUUID, arg.UserID, arg.SessionUuid)
	var i FindUserSessionByUserIDAndSessionUUIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserVersion,
		&i.SessionID,
		&i.AppID,
		&i.AccountID,
		&i.SessionUuid,
		&i.CreatedAt,
		&i.ID,
		&i.AccountID_2,
		&i.GrantID,
		&i.SessionID_2,
		&i.SessionType,
		&i.SessionClientID,
		&i.IpAddress,
		&i.UserAgent,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt_2,
		&i.UpdatedAt,
	)
	return i, err
}
