// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_auth_providers.sql

package database

import (
	"context"
)

const createUserAuthProvider = `-- name: CreateUserAuthProvider :exec

INSERT INTO "user_auth_providers" (
  "account_id",
  "user_id",
  "provider"
) VALUES (
  $1,
  $2,
  $3
)
`

type CreateUserAuthProviderParams struct {
	AccountID int32
	UserID    int32
	Provider  string
}

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) CreateUserAuthProvider(ctx context.Context, arg CreateUserAuthProviderParams) error {
	_, err := q.db.Exec(ctx, createUserAuthProvider, arg.AccountID, arg.UserID, arg.Provider)
	return err
}
