// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_totps.sql

package database

import (
	"context"
)

const findUserTotpByUserID = `-- name: FindUserTotpByUserID :one

SELECT id, account_id, user_id, url, secret, recovery_codes, created_at, updated_at FROM "user_totps"
WHERE "user_id" = $1 LIMIT 1
`

// Copyright (c) 2025 Afonso Barracha
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
func (q *Queries) FindUserTotpByUserID(ctx context.Context, userID int32) (UserTotp, error) {
	row := q.db.QueryRow(ctx, findUserTotpByUserID, userID)
	var i UserTotp
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Url,
		&i.Secret,
		&i.RecoveryCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
