// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	Password    pgtype.Text
	Version     int32
	IsConfirmed bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type AuthProvider struct {
	ID        int32
	Email     string
	Provider  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	AccountID int32
	Name      string
	Username  string
	Email     string
	Password  pgtype.Text
	Version   int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserAuthProvider struct {
	ID        int32
	Email     string
	Provider  string
	AccountID int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
